/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox UserInterface                          *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala, Alden Peterson, Lee Zaniewski, Jonathan Flory    *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FunctionComponentPanel
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFUNCTIONCOMPONENTPANELBASE_H_
#define _OSGFUNCTIONCOMPONENTPANELBASE_H_
#ifdef __sgi
#pragma once
#endif


#include <OpenSG/OSGConfig.h>
#include "OSGUserInterfaceDef.h"

#include <OpenSG/OSGBaseTypes.h>
#include <OpenSG/OSGRefPtr.h>
#include <OpenSG/OSGCoredNodePtr.h>

#include "Component/Container/OSGContainer.h" // Parent

#include <OpenSG/OSGReal32Fields.h> // Zoom type
#include <OpenSG/OSGBoolFields.h> // DrawMiniMap type
#include <OpenSG/OSGReal32Fields.h> // MiniMapSize type
#include <OpenSG/OSGVec2fFields.h> // MiniMapAlignment type
#include <OpenSG/OSGVec2fFields.h> // ZoomedPreferredSize type
#include <OpenSG/OSGPnt2fFields.h> // ChildrenPositions type
#include <OpenSG/OSGVec2fFields.h> // ChildrenSizes type
#include <OpenSG/OSGColor4fFields.h> // ResizeTabsColor type
#include <OpenSG/OSGVec2fFields.h> // ResizeTabsSize type
#include <OpenSG/OSGVec2fFields.h> // ResizeAreaOfEffectOffset type

#include "OSGFunctionComponentPanelFields.h"

OSG_BEGIN_NAMESPACE

class FunctionComponentPanel;
class BinaryDataHandler;

//! \brief FunctionComponentPanel Base Class.

class OSG_USERINTERFACELIB_DLLMAPPING FunctionComponentPanelBase : public Container
{
  private:

    typedef Container    Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    typedef FunctionComponentPanelPtr  Ptr;

    enum
    {
        ZoomFieldId                     = Inherited::NextFieldId,
        DrawMiniMapFieldId              = ZoomFieldId                     + 1,
        MiniMapSizeFieldId              = DrawMiniMapFieldId              + 1,
        MiniMapAlignmentFieldId         = MiniMapSizeFieldId              + 1,
        ZoomedPreferredSizeFieldId      = MiniMapAlignmentFieldId         + 1,
        ChildrenPositionsFieldId        = ZoomedPreferredSizeFieldId      + 1,
        ChildrenSizesFieldId            = ChildrenPositionsFieldId        + 1,
        ResizeTabsColorFieldId          = ChildrenSizesFieldId            + 1,
        ResizeTabsSizeFieldId           = ResizeTabsColorFieldId          + 1,
        ResizeAreaOfEffectOffsetFieldId = ResizeTabsSizeFieldId           + 1,
        NextFieldId                     = ResizeAreaOfEffectOffsetFieldId + 1
    };

    static const OSG::BitVector ZoomFieldMask;
    static const OSG::BitVector DrawMiniMapFieldMask;
    static const OSG::BitVector MiniMapSizeFieldMask;
    static const OSG::BitVector MiniMapAlignmentFieldMask;
    static const OSG::BitVector ZoomedPreferredSizeFieldMask;
    static const OSG::BitVector ChildrenPositionsFieldMask;
    static const OSG::BitVector ChildrenSizesFieldMask;
    static const OSG::BitVector ResizeTabsColorFieldMask;
    static const OSG::BitVector ResizeTabsSizeFieldMask;
    static const OSG::BitVector ResizeAreaOfEffectOffsetFieldMask;


    static const OSG::BitVector MTInfluenceMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static        FieldContainerType &getClassType    (void); 
    static        UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

           SFReal32            *getSFZoom           (void);
           SFBool              *getSFDrawMiniMap    (void);
           SFReal32            *getSFMiniMapSize    (void);
           SFVec2f             *getSFMiniMapAlignment(void);
           SFColor4f           *getSFResizeTabsColor(void);
           SFVec2f             *getSFResizeTabsSize (void);
           SFVec2f             *getSFResizeAreaOfEffectOffset(void);

           Real32              &getZoom           (void);
     const Real32              &getZoom           (void) const;
           bool                &getDrawMiniMap    (void);
     const bool                &getDrawMiniMap    (void) const;
           Real32              &getMiniMapSize    (void);
     const Real32              &getMiniMapSize    (void) const;
           Vec2f               &getMiniMapAlignment(void);
     const Vec2f               &getMiniMapAlignment(void) const;
           Color4f             &getResizeTabsColor(void);
     const Color4f             &getResizeTabsColor(void) const;
           Vec2f               &getResizeTabsSize (void);
     const Vec2f               &getResizeTabsSize (void) const;
           Vec2f               &getResizeAreaOfEffectOffset(void);
     const Vec2f               &getResizeAreaOfEffectOffset(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

     void setZoom           ( const Real32 &value );
     void setDrawMiniMap    ( const bool &value );
     void setMiniMapSize    ( const Real32 &value );
     void setMiniMapAlignment( const Vec2f &value );
     void setResizeTabsColor( const Color4f &value );
     void setResizeTabsSize ( const Vec2f &value );
     void setResizeAreaOfEffectOffset( const Vec2f &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (const BitVector         &whichField);
    virtual void   copyToBin  (      BinaryDataHandler &pMem,
                               const BitVector         &whichField);
    virtual void   copyFromBin(      BinaryDataHandler &pMem,
                               const BitVector         &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  FunctionComponentPanelPtr      create          (void); 
    static  FunctionComponentPanelPtr      createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFReal32            _sfZoom;
    SFBool              _sfDrawMiniMap;
    SFReal32            _sfMiniMapSize;
    SFVec2f             _sfMiniMapAlignment;
    SFVec2f             _sfZoomedPreferredSize;
    MFPnt2f             _mfChildrenPositions;
    MFVec2f             _mfChildrenSizes;
    SFColor4f           _sfResizeTabsColor;
    SFVec2f             _sfResizeTabsSize;
    SFVec2f             _sfResizeAreaOfEffectOffset;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    FunctionComponentPanelBase(void);
    FunctionComponentPanelBase(const FunctionComponentPanelBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~FunctionComponentPanelBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

           SFVec2f             *getSFZoomedPreferredSize(void);
           MFPnt2f             *getMFChildrenPositions(void);
           MFVec2f             *getMFChildrenSizes  (void);

           Vec2f               &getZoomedPreferredSize(void);
     const Vec2f               &getZoomedPreferredSize(void) const;
           Pnt2f               &getChildrenPositions(UInt32 index);
           MFPnt2f             &getChildrenPositions(void);
     const MFPnt2f             &getChildrenPositions(void) const;
           Vec2f               &getChildrenSizes  (UInt32 index);
           MFVec2f             &getChildrenSizes  (void);
     const MFVec2f             &getChildrenSizes  (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

     void setZoomedPreferredSize(const Vec2f &value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#if !defined(OSG_FIXED_MFIELDSYNC)
    void executeSyncImpl(      FunctionComponentPanelBase *pOther,
                         const BitVector         &whichField);

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField);
#else
    void executeSyncImpl(      FunctionComponentPanelBase *pOther,
                         const BitVector         &whichField,
                         const SyncInfo          &sInfo     );

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField,
                               const SyncInfo          &sInfo);

    virtual void execBeginEdit     (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

            void execBeginEditImpl (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

    virtual void onDestroyAspect(UInt32 uiId, UInt32 uiAspect);
#endif

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const FunctionComponentPanelBase &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef FunctionComponentPanelBase *FunctionComponentPanelBaseP;

typedef osgIF<FunctionComponentPanelBase::isNodeCore,
              CoredNodePtr<FunctionComponentPanel>,
              FieldContainer::attempt_to_create_CoredNodePtr_on_non_NodeCore_FC
              >::_IRet FunctionComponentPanelNodePtr;

typedef RefPtr<FunctionComponentPanelPtr> FunctionComponentPanelRefPtr;

OSG_END_NAMESPACE

#define OSGFUNCTIONCOMPONENTPANELBASE_HEADER_CVSID "@(#)$Id: FCBaseTemplate_h.h,v 1.40 2005/07/20 00:10:14 vossg Exp $"

#endif /* _OSGFUNCTIONCOMPONENTPANELBASE_H_ */
