/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class EventDetails!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGFieldContainer.h"          // Source Class

#include "OSGEventDetailsBase.h"
#include "OSGEventDetails.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::EventDetails
    Abstract Base class for EventDetails Objects.  EventDetails containers should contain only read-only fields.  They are used to pass the state information for EventProducers.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var FieldContainer * EventDetailsBase::_sfSource
    The Field Container that this event was produced on.
*/

/*! \var Time            EventDetailsBase::_sfTimeStamp
    The Timestamp of when this Event was produced.
*/

/*! \var bool            EventDetailsBase::_sfConsumed
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<EventDetails *>::_type("EventDetailsPtr", "FieldContainerPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(EventDetails *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           EventDetails *,
                           0);


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void EventDetailsBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecFieldContainerPtr::Description(
        SFUnrecFieldContainerPtr::getClassType(),
        "Source",
        "The Field Container that this event was produced on.\n",
        SourceFieldId, SourceFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&EventDetails::editHandleSource),
        static_cast<FieldGetMethodSig >(&EventDetails::getHandleSource));

    oType.addInitialDesc(pDesc);

    pDesc = new SFTime::Description(
        SFTime::getClassType(),
        "TimeStamp",
        "The Timestamp of when this Event was produced.\n",
        TimeStampFieldId, TimeStampFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&EventDetails::editHandleTimeStamp),
        static_cast<FieldGetMethodSig >(&EventDetails::getHandleTimeStamp));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "Consumed",
        "",
        ConsumedFieldId, ConsumedFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&EventDetails::editHandleConsumed),
        static_cast<FieldGetMethodSig >(&EventDetails::getHandleConsumed));

    oType.addInitialDesc(pDesc);
}


EventDetailsBase::TypeObject EventDetailsBase::_type(
    EventDetailsBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    NULL,
    EventDetails::initMethod,
    EventDetails::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&EventDetails::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"EventDetails\"\n"
    "\tparent=\"FieldContainer\"\n"
    "    library=\"Base\"\n"
    "\tpointerfieldtypes=\"single\"\n"
    "\tstructure=\"abstract\"\n"
    "\tsystemcomponent=\"true\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "\tsupportUnregisteredCreate=\"true\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "Abstract Base class for EventDetails Objects.  EventDetails containers should contain only read-only fields.  They are used to pass the state information for EventProducers.\n"
    "\t<Field\n"
    "        name=\"Source\"\n"
    "        type=\"FieldContainer\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"protected\"\n"
    "        defaultValue=\"NULL\"\n"
    "        publicRead=\"true\"\n"
    "        >\n"
    "        The Field Container that this event was produced on.\n"
    "\t</Field>\n"
    "\t<Field\n"
    "\t\tname=\"TimeStamp\"\n"
    "\t\ttype=\"Time\"\n"
    "        category=\"data\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"internal\"\n"
    "\t\taccess=\"protected\"\n"
    "\t\tdefaultValue=\"0\"\n"
    "        publicRead=\"true\"\n"
    "\t>\n"
    "    The Timestamp of when this Event was produced.\n"
    "\t</Field>\n"
    "\t<Field\n"
    "\t\tname=\"Consumed\"\n"
    "\t\ttype=\"bool\"\n"
    "        publicRead=\"true\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"internal\"\n"
    "\t\taccess=\"public\"\n"
    "\t\tdefaultValue=\"false\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    "Abstract Base class for EventDetails Objects.  EventDetails containers should contain only read-only fields.  They are used to pass the state information for EventProducers.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &EventDetailsBase::getType(void)
{
    return _type;
}

const FieldContainerType &EventDetailsBase::getType(void) const
{
    return _type;
}

UInt32 EventDetailsBase::getContainerSize(void) const
{
    return sizeof(EventDetails);
}

/*------------------------- decorator get ------------------------------*/


//! Get the EventDetails::_sfSource field.
const SFUnrecFieldContainerPtr *EventDetailsBase::getSFSource(void) const
{
    return &_sfSource;
}

SFUnrecFieldContainerPtr *EventDetailsBase::editSFSource         (void)
{
    editSField(SourceFieldMask);

    return &_sfSource;
}

SFTime *EventDetailsBase::editSFTimeStamp(void)
{
    editSField(TimeStampFieldMask);

    return &_sfTimeStamp;
}

const SFTime *EventDetailsBase::getSFTimeStamp(void) const
{
    return &_sfTimeStamp;
}


SFBool *EventDetailsBase::editSFConsumed(void)
{
    editSField(ConsumedFieldMask);

    return &_sfConsumed;
}

const SFBool *EventDetailsBase::getSFConsumed(void) const
{
    return &_sfConsumed;
}






/*------------------------------ access -----------------------------------*/

UInt32 EventDetailsBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (SourceFieldMask & whichField))
    {
        returnValue += _sfSource.getBinSize();
    }
    if(FieldBits::NoField != (TimeStampFieldMask & whichField))
    {
        returnValue += _sfTimeStamp.getBinSize();
    }
    if(FieldBits::NoField != (ConsumedFieldMask & whichField))
    {
        returnValue += _sfConsumed.getBinSize();
    }

    return returnValue;
}

void EventDetailsBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (SourceFieldMask & whichField))
    {
        _sfSource.copyToBin(pMem);
    }
    if(FieldBits::NoField != (TimeStampFieldMask & whichField))
    {
        _sfTimeStamp.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ConsumedFieldMask & whichField))
    {
        _sfConsumed.copyToBin(pMem);
    }
}

void EventDetailsBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (SourceFieldMask & whichField))
    {
        _sfSource.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (TimeStampFieldMask & whichField))
    {
        _sfTimeStamp.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ConsumedFieldMask & whichField))
    {
        _sfConsumed.copyFromBin(pMem);
    }
}



/*------------------------- constructors ----------------------------------*/

EventDetailsBase::EventDetailsBase(void) :
    Inherited(),
    _sfSource                 (NULL),
    _sfTimeStamp              (Time(0)),
    _sfConsumed               (bool(false))
{
}

EventDetailsBase::EventDetailsBase(const EventDetailsBase &source) :
    Inherited(source),
    _sfSource                 (NULL),
    _sfTimeStamp              (source._sfTimeStamp              ),
    _sfConsumed               (source._sfConsumed               )
{
}


/*-------------------------- destructors ----------------------------------*/

EventDetailsBase::~EventDetailsBase(void)
{
}

void EventDetailsBase::onCreate(const EventDetails *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        EventDetails *pThis = static_cast<EventDetails *>(this);

        pThis->setSource(source->getSource());
    }
}

GetFieldHandlePtr EventDetailsBase::getHandleSource          (void) const
{
    SFUnrecFieldContainerPtr::GetHandlePtr returnValue(
        new  SFUnrecFieldContainerPtr::GetHandle(
             &_sfSource,
             this->getType().getFieldDesc(SourceFieldId),
             const_cast<EventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr EventDetailsBase::editHandleSource         (void)
{
    SFUnrecFieldContainerPtr::EditHandlePtr returnValue(
        new  SFUnrecFieldContainerPtr::EditHandle(
             &_sfSource,
             this->getType().getFieldDesc(SourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&EventDetails::setSource,
                    static_cast<EventDetails *>(this), _1));

    editSField(SourceFieldMask);

    return returnValue;
}

GetFieldHandlePtr EventDetailsBase::getHandleTimeStamp       (void) const
{
    SFTime::GetHandlePtr returnValue(
        new  SFTime::GetHandle(
             &_sfTimeStamp,
             this->getType().getFieldDesc(TimeStampFieldId),
             const_cast<EventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr EventDetailsBase::editHandleTimeStamp      (void)
{
    SFTime::EditHandlePtr returnValue(
        new  SFTime::EditHandle(
             &_sfTimeStamp,
             this->getType().getFieldDesc(TimeStampFieldId),
             this));


    editSField(TimeStampFieldMask);

    return returnValue;
}

GetFieldHandlePtr EventDetailsBase::getHandleConsumed        (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfConsumed,
             this->getType().getFieldDesc(ConsumedFieldId),
             const_cast<EventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr EventDetailsBase::editHandleConsumed       (void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfConsumed,
             this->getType().getFieldDesc(ConsumedFieldId),
             this));


    editSField(ConsumedFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void EventDetailsBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    EventDetails *pThis = static_cast<EventDetails *>(this);

    pThis->execSync(static_cast<EventDetails *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void EventDetailsBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<EventDetails *>(this)->setSource(NULL);


}


OSG_END_NAMESPACE
