/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGEVENTDETAILSFIELDS_H_
#define _OSGEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class EventDetails;

OSG_GEN_CONTAINERPTR(EventDetails);

/*! \ingroup GrpBaseFieldTraits
    \ingroup GrpLibOSGBase
 */
template <>
struct FieldTraits<EventDetails *> :
    public FieldTraitsFCPtrBase<EventDetails *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<EventDetails *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFEventDetailsPtr"; }
};

template<> inline
const Char8 *FieldTraits<EventDetails *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventDetails *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventDetails *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventDetails *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdEventDetailsPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<EventDetails *,
                      RecordedRefCountPolicy  > SFRecEventDetailsPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<EventDetails *,
                      UnrecordedRefCountPolicy> SFUnrecEventDetailsPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<EventDetails *,
                      WeakRefCountPolicy      > SFWeakEventDetailsPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<EventDetails *,
                      NoRefCountPolicy        > SFUncountedEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFRecEventDetailsPtr : 
    public PointerSField<EventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFUnrecEventDetailsPtr : 
    public PointerSField<EventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFWeakEventDetailsPtr :
    public PointerSField<EventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFUncountedEventDetailsPtr :
    public PointerSField<EventDetails *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGEVENTDETAILSFIELDS_H_ */
