/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFIELDCHANGEEVENTFIELDS_H_
#define _OSGFIELDCHANGEEVENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class FieldChangeEvent;

OSG_GEN_CONTAINERPTR(FieldChangeEvent);

/*! \ingroup GrpBaseFieldTraits
    \ingroup GrpLibOSGBase
 */
template <>
struct FieldTraits<FieldChangeEvent *> :
    public FieldTraitsFCPtrBase<FieldChangeEvent *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<FieldChangeEvent *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFFieldChangeEventPtr"; }
};

template<> inline
const Char8 *FieldTraits<FieldChangeEvent *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecFieldChangeEventPtr"; 
}

template<> inline
const Char8 *FieldTraits<FieldChangeEvent *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecFieldChangeEventPtr"; 
}

template<> inline
const Char8 *FieldTraits<FieldChangeEvent *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakFieldChangeEventPtr"; 
}

template<> inline
const Char8 *FieldTraits<FieldChangeEvent *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdFieldChangeEventPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<FieldChangeEvent *,
                      RecordedRefCountPolicy  > SFRecFieldChangeEventPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<FieldChangeEvent *,
                      UnrecordedRefCountPolicy> SFUnrecFieldChangeEventPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<FieldChangeEvent *,
                      WeakRefCountPolicy      > SFWeakFieldChangeEventPtr;
/*! \ingroup GrpBaseFieldSFields */
typedef PointerSField<FieldChangeEvent *,
                      NoRefCountPolicy        > SFUncountedFieldChangeEventPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFRecFieldChangeEventPtr : 
    public PointerSField<FieldChangeEvent *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFUnrecFieldChangeEventPtr : 
    public PointerSField<FieldChangeEvent *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFWeakFieldChangeEventPtr :
    public PointerSField<FieldChangeEvent *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldSFields \ingroup GrpLibOSGBase */
struct SFUncountedFieldChangeEventPtr :
    public PointerSField<FieldChangeEvent *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGFIELDCHANGEEVENTFIELDS_H_ */
