/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTUREDQUADUIDRAWOBJECTFIELDS_H_
#define _OSGTEXTUREDQUADUIDRAWOBJECTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TexturedQuadUIDrawObject;

OSG_GEN_CONTAINERPTR(TexturedQuadUIDrawObject);

/*! \ingroup GrpContribUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribUserInterface
 */
template <>
struct FieldTraits<TexturedQuadUIDrawObject *> :
    public FieldTraitsFCPtrBase<TexturedQuadUIDrawObject *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TexturedQuadUIDrawObject *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTexturedQuadUIDrawObjectPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTexturedQuadUIDrawObjectPtr"; }
};

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTexturedQuadUIDrawObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTexturedQuadUIDrawObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTexturedQuadUIDrawObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTexturedQuadUIDrawObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTexturedQuadUIDrawObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTexturedQuadUIDrawObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTexturedQuadUIDrawObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<TexturedQuadUIDrawObject *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTexturedQuadUIDrawObjectPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<TexturedQuadUIDrawObject *,
                      RecordedRefCountPolicy  > SFRecTexturedQuadUIDrawObjectPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<TexturedQuadUIDrawObject *,
                      UnrecordedRefCountPolicy> SFUnrecTexturedQuadUIDrawObjectPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<TexturedQuadUIDrawObject *,
                      WeakRefCountPolicy      > SFWeakTexturedQuadUIDrawObjectPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<TexturedQuadUIDrawObject *,
                      NoRefCountPolicy        > SFUncountedTexturedQuadUIDrawObjectPtr;


/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<TexturedQuadUIDrawObject *,
                      RecordedRefCountPolicy  > MFRecTexturedQuadUIDrawObjectPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<TexturedQuadUIDrawObject *,
                      UnrecordedRefCountPolicy> MFUnrecTexturedQuadUIDrawObjectPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<TexturedQuadUIDrawObject *,
                      WeakRefCountPolicy      > MFWeakTexturedQuadUIDrawObjectPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<TexturedQuadUIDrawObject *,
                      NoRefCountPolicy        > MFUncountedTexturedQuadUIDrawObjectPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFRecTexturedQuadUIDrawObjectPtr : 
    public PointerSField<TexturedQuadUIDrawObject *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUnrecTexturedQuadUIDrawObjectPtr : 
    public PointerSField<TexturedQuadUIDrawObject *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFWeakTexturedQuadUIDrawObjectPtr :
    public PointerSField<TexturedQuadUIDrawObject *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUncountedTexturedQuadUIDrawObjectPtr :
    public PointerSField<TexturedQuadUIDrawObject *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFRecTexturedQuadUIDrawObjectPtr :
    public PointerMField<TexturedQuadUIDrawObject *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUnrecTexturedQuadUIDrawObjectPtr :
    public PointerMField<TexturedQuadUIDrawObject *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFWeakTexturedQuadUIDrawObjectPtr :
    public PointerMField<TexturedQuadUIDrawObject *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUncountedTexturedQuadUIDrawObjectPtr :
    public PointerMField<TexturedQuadUIDrawObject *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTUREDQUADUIDRAWOBJECTFIELDS_H_ */
