/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGLISTCOMPONENTGENERATORFIELDS_H_
#define _OSGLISTCOMPONENTGENERATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class ListComponentGenerator;

OSG_GEN_CONTAINERPTR(ListComponentGenerator);

/*! \ingroup GrpContribUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribUserInterface
 */
template <>
struct FieldTraits<ListComponentGenerator *> :
    public FieldTraitsFCPtrBase<ListComponentGenerator *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ListComponentGenerator *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFListComponentGeneratorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFListComponentGeneratorPtr"; }
};

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecListComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecListComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakListComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdListComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecListComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecListComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakListComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListComponentGenerator *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdListComponentGeneratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ListComponentGenerator *,
                      RecordedRefCountPolicy  > SFRecListComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ListComponentGenerator *,
                      UnrecordedRefCountPolicy> SFUnrecListComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ListComponentGenerator *,
                      WeakRefCountPolicy      > SFWeakListComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<ListComponentGenerator *,
                      NoRefCountPolicy        > SFUncountedListComponentGeneratorPtr;


/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ListComponentGenerator *,
                      RecordedRefCountPolicy  > MFRecListComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ListComponentGenerator *,
                      UnrecordedRefCountPolicy> MFUnrecListComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ListComponentGenerator *,
                      WeakRefCountPolicy      > MFWeakListComponentGeneratorPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<ListComponentGenerator *,
                      NoRefCountPolicy        > MFUncountedListComponentGeneratorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFRecListComponentGeneratorPtr : 
    public PointerSField<ListComponentGenerator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUnrecListComponentGeneratorPtr : 
    public PointerSField<ListComponentGenerator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFWeakListComponentGeneratorPtr :
    public PointerSField<ListComponentGenerator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUncountedListComponentGeneratorPtr :
    public PointerSField<ListComponentGenerator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFRecListComponentGeneratorPtr :
    public PointerMField<ListComponentGenerator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUnrecListComponentGeneratorPtr :
    public PointerMField<ListComponentGenerator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFWeakListComponentGeneratorPtr :
    public PointerMField<ListComponentGenerator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUncountedListComponentGeneratorPtr :
    public PointerMField<ListComponentGenerator *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGLISTCOMPONENTGENERATORFIELDS_H_ */
