/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FModSound!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGFModSoundBase.h"
#include "OSGFModSound.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::FModSound
    A FMod Sound Interface.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<FModSound *>::_type("FModSoundPtr", "SoundPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(FModSound *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           FModSound *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           FModSound *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void FModSoundBase::classDescInserter(TypeObject &oType)
{
}


FModSoundBase::TypeObject FModSoundBase::_type(
    FModSoundBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&FModSoundBase::createEmptyLocal),
    FModSound::initMethod,
    FModSound::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&FModSound::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"FModSound\"\n"
    "\tparent=\"Sound\"\n"
    "    library=\"ContribSound\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A FMod Sound Interface.\n"
    "</FieldContainer>\n",
    "A FMod Sound Interface.\n"
    );


/*------------------------------ get -----------------------------------*/

FieldContainerType &FModSoundBase::getType(void)
{
    return _type;
}

const FieldContainerType &FModSoundBase::getType(void) const
{
    return _type;
}

UInt32 FModSoundBase::getContainerSize(void) const
{
    return sizeof(FModSound);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 FModSoundBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void FModSoundBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void FModSoundBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
FModSoundTransitPtr FModSoundBase::createLocal(BitVector bFlags)
{
    FModSoundTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<FModSound>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
FModSoundTransitPtr FModSoundBase::createDependent(BitVector bFlags)
{
    FModSoundTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<FModSound>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
FModSoundTransitPtr FModSoundBase::create(void)
{
    FModSoundTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<FModSound>(tmpPtr);
    }

    return fc;
}

FModSound *FModSoundBase::createEmptyLocal(BitVector bFlags)
{
    FModSound *returnValue;

    newPtr<FModSound>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
FModSound *FModSoundBase::createEmpty(void)
{
    FModSound *returnValue;

    newPtr<FModSound>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr FModSoundBase::shallowCopyLocal(
    BitVector bFlags) const
{
    FModSound *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const FModSound *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr FModSoundBase::shallowCopyDependent(
    BitVector bFlags) const
{
    FModSound *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const FModSound *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr FModSoundBase::shallowCopy(void) const
{
    FModSound *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const FModSound *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

FModSoundBase::FModSoundBase(void) :
    Inherited()
{
}

FModSoundBase::FModSoundBase(const FModSoundBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

FModSoundBase::~FModSoundBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void FModSoundBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    FModSound *pThis = static_cast<FModSound *>(this);

    pThis->execSync(static_cast<FModSound *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *FModSoundBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    FModSound *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const FModSound *>(pRefAspect),
                  dynamic_cast<const FModSound *>(this));

    return returnValue;
}
#endif

void FModSoundBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
