
MACRO(OSG_CONFIGURE_CG_TOOLKIT)

    IF(OSG_USE_OSGSUPPORT_LIBS AND WIN32)

      IF(EXISTS ${CG_ROOT}/include/CG/cg.h)
        SET(CG_TOOLKIT_INCLUDE_DIR ${CG_ROOT}/include CACHE PATH "" FORCE)
      ENDIF()

      IF(EXISTS ${CG_ROOT}/lib/libosgcg.lib)
        SET(CG_TOOLKIT_LIBRARY_RELEASE ${CG_ROOT}/lib/libosgcg.lib)
      ENDIF()
      IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/libosgjpgD.lib)
        SET(CG_TOOLKIT_LIBRARY_DEBUG ${CG_ROOT}/lib/libosgcgD.lib)
      ENDIF()

      IF(CG_TOOLKIT_INCLUDE_DIR)
        IF(CG_TOOLKIT_LIBRARY_DEBUG OR CG_TOOLKIT_LIBRARY_RELEASE)
          SET(CG_TOOLKIT_FOUND TRUE)
        ENDIF()
      ENDIF()

      IF(CG_TOOLKIT_FOUND)
        OSG_ADD_IMPORT_LIB(OSG_CG_TOOLKIT_TARGETS CG_TOOLKIT_LIBRARY)
        SET(CG_TOOLKIT_LIBRARIES ${OSG_CG_TOOLKIT_TARGETS} CACHE STRING "" FORCE)
      ENDIF(CG_TOOLKIT_FOUND)

    ENDIF(OSG_USE_OSGSUPPORT_LIBS AND WIN32)

    IF(NOT OSG_USE_OSGSUPPORT_LIBS OR NOT CG_TOOLKIT_FOUND)
      OSG_FIND_PACKAGE(CgToolkit_OpenSG)

      IF(CG_TOOLKIT_FOUND)
        OSG_ADD_IMPORT_LIB(OSG_CG_TOOLKIT_TARGETS CG_TOOLKIT_LIBRARY)

        SET(CG_TOOLKIT_LIBRARIES ${OSG_CG_TOOLKIT_TARGETS} CACHE STRING "" FORCE)
      ENDIF(CG_TOOLKIT_FOUND)
    ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS OR NOT CG_TOOLKIT_FOUND)

ENDMACRO(OSG_CONFIGURE_CG_TOOLKIT)

