/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class MatteBorder
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMATTEBORDERBASE_H_
#define _OSGMATTEBORDERBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

//#include "OSGBaseTypes.h"

#include "OSGBorder.h" // Parent

#include "OSGSysFields.h"               // LeftWidth type
#include "OSGBaseFields.h"              // Color type
#include "OSGMaterialFields.h"          // Material type

#include "OSGMatteBorderFields.h"

OSG_BEGIN_NAMESPACE

class MatteBorder;

//! \brief MatteBorder Base Class.

class OSG_CONTRIBUSERINTERFACE_DLLMAPPING MatteBorderBase : public Border
{
  public:

    typedef Border Inherited;
    typedef Border ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(MatteBorder);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        LeftWidthFieldId = Inherited::NextFieldId,
        RightWidthFieldId = LeftWidthFieldId + 1,
        TopWidthFieldId = RightWidthFieldId + 1,
        BottomWidthFieldId = TopWidthFieldId + 1,
        ColorFieldId = BottomWidthFieldId + 1,
        MaterialFieldId = ColorFieldId + 1,
        NextFieldId = MaterialFieldId + 1
    };

    static const OSG::BitVector LeftWidthFieldMask =
        (TypeTraits<BitVector>::One << LeftWidthFieldId);
    static const OSG::BitVector RightWidthFieldMask =
        (TypeTraits<BitVector>::One << RightWidthFieldId);
    static const OSG::BitVector TopWidthFieldMask =
        (TypeTraits<BitVector>::One << TopWidthFieldId);
    static const OSG::BitVector BottomWidthFieldMask =
        (TypeTraits<BitVector>::One << BottomWidthFieldId);
    static const OSG::BitVector ColorFieldMask =
        (TypeTraits<BitVector>::One << ColorFieldId);
    static const OSG::BitVector MaterialFieldMask =
        (TypeTraits<BitVector>::One << MaterialFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFReal32          SFLeftWidthType;
    typedef SFReal32          SFRightWidthType;
    typedef SFReal32          SFTopWidthType;
    typedef SFReal32          SFBottomWidthType;
    typedef SFColor4f         SFColorType;
    typedef SFUnrecMaterialPtr SFMaterialType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */


                  SFReal32            *editSFLeftWidth      (void);
            const SFReal32            *getSFLeftWidth       (void) const;

                  SFReal32            *editSFRightWidth     (void);
            const SFReal32            *getSFRightWidth      (void) const;

                  SFReal32            *editSFTopWidth       (void);
            const SFReal32            *getSFTopWidth        (void) const;

                  SFReal32            *editSFBottomWidth    (void);
            const SFReal32            *getSFBottomWidth     (void) const;

                  SFColor4f           *editSFColor          (void);
            const SFColor4f           *getSFColor           (void) const;
            const SFUnrecMaterialPtr  *getSFMaterial       (void) const;
                  SFUnrecMaterialPtr  *editSFMaterial       (void);


                  Real32              &editLeftWidth      (void);
                  Real32               getLeftWidth       (void) const;

                  Real32              &editRightWidth     (void);
                  Real32               getRightWidth      (void) const;

                  Real32              &editTopWidth       (void);
                  Real32               getTopWidth        (void) const;

                  Real32              &editBottomWidth    (void);
                  Real32               getBottomWidth     (void) const;

                  Color4f             &editColor          (void);
            const Color4f             &getColor           (void) const;

                  Material * getMaterial       (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setLeftWidth      (const Real32 value);
            void setRightWidth     (const Real32 value);
            void setTopWidth       (const Real32 value);
            void setBottomWidth    (const Real32 value);
            void setColor          (const Color4f &value);
            void setMaterial       (Material * const value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  MatteBorderTransitPtr  create          (void);
    static  MatteBorder           *createEmpty     (void);

    static  MatteBorderTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  MatteBorder            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  MatteBorderTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFReal32          _sfLeftWidth;
    SFReal32          _sfRightWidth;
    SFReal32          _sfTopWidth;
    SFReal32          _sfBottomWidth;
    SFColor4f         _sfColor;
    SFUnrecMaterialPtr _sfMaterial;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    MatteBorderBase(void);
    MatteBorderBase(const MatteBorderBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~MatteBorderBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const MatteBorder *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleLeftWidth       (void) const;
    EditFieldHandlePtr editHandleLeftWidth      (void);
    GetFieldHandlePtr  getHandleRightWidth      (void) const;
    EditFieldHandlePtr editHandleRightWidth     (void);
    GetFieldHandlePtr  getHandleTopWidth        (void) const;
    EditFieldHandlePtr editHandleTopWidth       (void);
    GetFieldHandlePtr  getHandleBottomWidth     (void) const;
    EditFieldHandlePtr editHandleBottomWidth    (void);
    GetFieldHandlePtr  getHandleColor           (void) const;
    EditFieldHandlePtr editHandleColor          (void);
    GetFieldHandlePtr  getHandleMaterial        (void) const;
    EditFieldHandlePtr editHandleMaterial       (void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      MatteBorderBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const MatteBorderBase &source);
};

typedef MatteBorderBase *MatteBorderBaseP;

OSG_END_NAMESPACE

#endif /* _OSGMATTEBORDERBASE_H_ */
