/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox UserInterface                          *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala, Alden Peterson, Lee Zaniewski, Jonathan Flory    *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DefaultTreeCellEditor
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDEFAULTTREECELLEDITORBASE_H_
#define _OSGDEFAULTTREECELLEDITORBASE_H_
#ifdef __sgi
#pragma once
#endif


#include <OpenSG/OSGConfig.h>
#include "OSGUserInterfaceDef.h"

#include <OpenSG/OSGBaseTypes.h>
#include <OpenSG/OSGRefPtr.h>
#include <OpenSG/OSGCoredNodePtr.h>

#include "OSGTreeCellEditor.h" // Parent

#include <OpenSG/OSGUInt32Fields.h> // ClickCountToStart type
#include "Component/Text/OSGTextFieldFields.h" // DefaultEditor type
#include "Component/Text/OSGTextFieldFields.h" // DefaultStringEditor type

#include "OSGDefaultTreeCellEditorFields.h"

OSG_BEGIN_NAMESPACE

class DefaultTreeCellEditor;
class BinaryDataHandler;

//! \brief DefaultTreeCellEditor Base Class.

class OSG_USERINTERFACELIB_DLLMAPPING DefaultTreeCellEditorBase : public TreeCellEditor
{
  private:

    typedef TreeCellEditor    Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    typedef DefaultTreeCellEditorPtr  Ptr;

    enum
    {
        ClickCountToStartFieldId   = Inherited::NextFieldId,
        DefaultEditorFieldId       = ClickCountToStartFieldId   + 1,
        DefaultStringEditorFieldId = DefaultEditorFieldId       + 1,
        NextFieldId                = DefaultStringEditorFieldId + 1
    };

    static const OSG::BitVector ClickCountToStartFieldMask;
    static const OSG::BitVector DefaultEditorFieldMask;
    static const OSG::BitVector DefaultStringEditorFieldMask;


    static const OSG::BitVector MTInfluenceMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static        FieldContainerType &getClassType    (void); 
    static        UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

           SFUInt32            *getSFClickCountToStart(void);
           SFTextFieldPtr      *getSFDefaultEditor  (void);
           SFTextFieldPtr      *getSFDefaultStringEditor(void);

           UInt32              &getClickCountToStart(void);
     const UInt32              &getClickCountToStart(void) const;
           TextFieldPtr        &getDefaultEditor  (void);
     const TextFieldPtr        &getDefaultEditor  (void) const;
           TextFieldPtr        &getDefaultStringEditor(void);
     const TextFieldPtr        &getDefaultStringEditor(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

     void setClickCountToStart( const UInt32 &value );
     void setDefaultEditor  ( const TextFieldPtr &value );
     void setDefaultStringEditor( const TextFieldPtr &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (const BitVector         &whichField);
    virtual void   copyToBin  (      BinaryDataHandler &pMem,
                               const BitVector         &whichField);
    virtual void   copyFromBin(      BinaryDataHandler &pMem,
                               const BitVector         &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  DefaultTreeCellEditorPtr      create          (void); 
    static  DefaultTreeCellEditorPtr      createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFUInt32            _sfClickCountToStart;
    SFTextFieldPtr      _sfDefaultEditor;
    SFTextFieldPtr      _sfDefaultStringEditor;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    DefaultTreeCellEditorBase(void);
    DefaultTreeCellEditorBase(const DefaultTreeCellEditorBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~DefaultTreeCellEditorBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#if !defined(OSG_FIXED_MFIELDSYNC)
    void executeSyncImpl(      DefaultTreeCellEditorBase *pOther,
                         const BitVector         &whichField);

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField);
#else
    void executeSyncImpl(      DefaultTreeCellEditorBase *pOther,
                         const BitVector         &whichField,
                         const SyncInfo          &sInfo     );

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField,
                               const SyncInfo          &sInfo);

    virtual void execBeginEdit     (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

            void execBeginEditImpl (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

    virtual void onDestroyAspect(UInt32 uiId, UInt32 uiAspect);
#endif

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const DefaultTreeCellEditorBase &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef DefaultTreeCellEditorBase *DefaultTreeCellEditorBaseP;

typedef osgIF<DefaultTreeCellEditorBase::isNodeCore,
              CoredNodePtr<DefaultTreeCellEditor>,
              FieldContainer::attempt_to_create_CoredNodePtr_on_non_NodeCore_FC
              >::_IRet DefaultTreeCellEditorNodePtr;

typedef RefPtr<DefaultTreeCellEditorPtr> DefaultTreeCellEditorRefPtr;

OSG_END_NAMESPACE

#define OSGDEFAULTTREECELLEDITORBASE_HEADER_CVSID "@(#)$Id: FCBaseTemplate_h.h,v 1.40 2005/07/20 00:10:14 vossg Exp $"

#endif /* _OSGDEFAULTTREECELLEDITORBASE_H_ */
