/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox UserInterface                          *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *                          Authors: David Kabala                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BlendedKeyframeAnimator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEBLENDEDKEYFRAMEANIMATORINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGBlendedKeyframeAnimatorBase.h"
#include "OSGBlendedKeyframeAnimator.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  BlendedKeyframeAnimatorBase::KeyframeSequencesFieldMask = 
    (TypeTraits<BitVector>::One << BlendedKeyframeAnimatorBase::KeyframeSequencesFieldId);

const OSG::BitVector  BlendedKeyframeAnimatorBase::BlendAmountsFieldMask = 
    (TypeTraits<BitVector>::One << BlendedKeyframeAnimatorBase::BlendAmountsFieldId);

const OSG::BitVector BlendedKeyframeAnimatorBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var KeyframeSequencePtr BlendedKeyframeAnimatorBase::_mfKeyframeSequences
    
*/
/*! \var Real32          BlendedKeyframeAnimatorBase::_mfBlendAmounts
    
*/

//! BlendedKeyframeAnimator description

FieldDescription *BlendedKeyframeAnimatorBase::_desc[] = 
{
    new FieldDescription(MFKeyframeSequencePtr::getClassType(), 
                     "KeyframeSequences", 
                     KeyframeSequencesFieldId, KeyframeSequencesFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&BlendedKeyframeAnimatorBase::editMFKeyframeSequences)),
    new FieldDescription(MFReal32::getClassType(), 
                     "BlendAmounts", 
                     BlendAmountsFieldId, BlendAmountsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&BlendedKeyframeAnimatorBase::editMFBlendAmounts))
};


FieldContainerType BlendedKeyframeAnimatorBase::_type(
    "BlendedKeyframeAnimator",
    "Animator",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&BlendedKeyframeAnimatorBase::createEmpty),
    BlendedKeyframeAnimator::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(BlendedKeyframeAnimatorBase, BlendedKeyframeAnimatorPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &BlendedKeyframeAnimatorBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &BlendedKeyframeAnimatorBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr BlendedKeyframeAnimatorBase::shallowCopy(void) const 
{ 
    BlendedKeyframeAnimatorPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const BlendedKeyframeAnimator *>(this)); 

    return returnValue; 
}

UInt32 BlendedKeyframeAnimatorBase::getContainerSize(void) const 
{ 
    return sizeof(BlendedKeyframeAnimator); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void BlendedKeyframeAnimatorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<BlendedKeyframeAnimatorBase *>(&other),
                          whichField);
}
#else
void BlendedKeyframeAnimatorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((BlendedKeyframeAnimatorBase *) &other, whichField, sInfo);
}
void BlendedKeyframeAnimatorBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void BlendedKeyframeAnimatorBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

    _mfKeyframeSequences.terminateShare(uiAspect, this->getContainerSize());
    _mfBlendAmounts.terminateShare(uiAspect, this->getContainerSize());
}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

BlendedKeyframeAnimatorBase::BlendedKeyframeAnimatorBase(void) :
    _mfKeyframeSequences      (), 
    _mfBlendAmounts           (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

BlendedKeyframeAnimatorBase::BlendedKeyframeAnimatorBase(const BlendedKeyframeAnimatorBase &source) :
    _mfKeyframeSequences      (source._mfKeyframeSequences      ), 
    _mfBlendAmounts           (source._mfBlendAmounts           ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

BlendedKeyframeAnimatorBase::~BlendedKeyframeAnimatorBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 BlendedKeyframeAnimatorBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (KeyframeSequencesFieldMask & whichField))
    {
        returnValue += _mfKeyframeSequences.getBinSize();
    }

    if(FieldBits::NoField != (BlendAmountsFieldMask & whichField))
    {
        returnValue += _mfBlendAmounts.getBinSize();
    }


    return returnValue;
}

void BlendedKeyframeAnimatorBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (KeyframeSequencesFieldMask & whichField))
    {
        _mfKeyframeSequences.copyToBin(pMem);
    }

    if(FieldBits::NoField != (BlendAmountsFieldMask & whichField))
    {
        _mfBlendAmounts.copyToBin(pMem);
    }


}

void BlendedKeyframeAnimatorBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (KeyframeSequencesFieldMask & whichField))
    {
        _mfKeyframeSequences.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (BlendAmountsFieldMask & whichField))
    {
        _mfBlendAmounts.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void BlendedKeyframeAnimatorBase::executeSyncImpl(      BlendedKeyframeAnimatorBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (KeyframeSequencesFieldMask & whichField))
        _mfKeyframeSequences.syncWith(pOther->_mfKeyframeSequences);

    if(FieldBits::NoField != (BlendAmountsFieldMask & whichField))
        _mfBlendAmounts.syncWith(pOther->_mfBlendAmounts);


}
#else
void BlendedKeyframeAnimatorBase::executeSyncImpl(      BlendedKeyframeAnimatorBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);


    if(FieldBits::NoField != (KeyframeSequencesFieldMask & whichField))
        _mfKeyframeSequences.syncWith(pOther->_mfKeyframeSequences, sInfo);

    if(FieldBits::NoField != (BlendAmountsFieldMask & whichField))
        _mfBlendAmounts.syncWith(pOther->_mfBlendAmounts, sInfo);


}

void BlendedKeyframeAnimatorBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

    if(FieldBits::NoField != (KeyframeSequencesFieldMask & whichField))
        _mfKeyframeSequences.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (BlendAmountsFieldMask & whichField))
        _mfBlendAmounts.beginEdit(uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<BlendedKeyframeAnimatorPtr>::_type("BlendedKeyframeAnimatorPtr", "AnimatorPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(BlendedKeyframeAnimatorPtr, OSG_ANIMATIONLIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(BlendedKeyframeAnimatorPtr, OSG_ANIMATIONLIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

