/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox Particle System                        *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *                          Authors: David Kabala                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ConserveVelocityParticleAffector!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILECONSERVEVELOCITYPARTICLEAFFECTORINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGConserveVelocityParticleAffectorBase.h"
#include "OSGConserveVelocityParticleAffector.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  ConserveVelocityParticleAffectorBase::ConserveFieldMask = 
    (TypeTraits<BitVector>::One << ConserveVelocityParticleAffectorBase::ConserveFieldId);

const OSG::BitVector ConserveVelocityParticleAffectorBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var Real32          ConserveVelocityParticleAffectorBase::_sfConserve
    
*/

//! ConserveVelocityParticleAffector description

FieldDescription *ConserveVelocityParticleAffectorBase::_desc[] = 
{
    new FieldDescription(SFReal32::getClassType(), 
                     "Conserve", 
                     ConserveFieldId, ConserveFieldMask,
                     false,
                     (FieldAccessMethod) &ConserveVelocityParticleAffectorBase::getSFConserve)
};


FieldContainerType ConserveVelocityParticleAffectorBase::_type(
    "ConserveVelocityParticleAffector",
    "ParticleAffector",
    NULL,
    (PrototypeCreateF) &ConserveVelocityParticleAffectorBase::createEmpty,
    ConserveVelocityParticleAffector::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(ConserveVelocityParticleAffectorBase, ConserveVelocityParticleAffectorPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &ConserveVelocityParticleAffectorBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ConserveVelocityParticleAffectorBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr ConserveVelocityParticleAffectorBase::shallowCopy(void) const 
{ 
    ConserveVelocityParticleAffectorPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const ConserveVelocityParticleAffector *>(this)); 

    return returnValue; 
}

UInt32 ConserveVelocityParticleAffectorBase::getContainerSize(void) const 
{ 
    return sizeof(ConserveVelocityParticleAffector); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void ConserveVelocityParticleAffectorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((ConserveVelocityParticleAffectorBase *) &other, whichField);
}
#else
void ConserveVelocityParticleAffectorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((ConserveVelocityParticleAffectorBase *) &other, whichField, sInfo);
}
void ConserveVelocityParticleAffectorBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void ConserveVelocityParticleAffectorBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

ConserveVelocityParticleAffectorBase::ConserveVelocityParticleAffectorBase(void) :
    _sfConserve               (Real32(1.000)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

ConserveVelocityParticleAffectorBase::ConserveVelocityParticleAffectorBase(const ConserveVelocityParticleAffectorBase &source) :
    _sfConserve               (source._sfConserve               ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

ConserveVelocityParticleAffectorBase::~ConserveVelocityParticleAffectorBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 ConserveVelocityParticleAffectorBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ConserveFieldMask & whichField))
    {
        returnValue += _sfConserve.getBinSize();
    }


    return returnValue;
}

void ConserveVelocityParticleAffectorBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ConserveFieldMask & whichField))
    {
        _sfConserve.copyToBin(pMem);
    }


}

void ConserveVelocityParticleAffectorBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ConserveFieldMask & whichField))
    {
        _sfConserve.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void ConserveVelocityParticleAffectorBase::executeSyncImpl(      ConserveVelocityParticleAffectorBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (ConserveFieldMask & whichField))
        _sfConserve.syncWith(pOther->_sfConserve);


}
#else
void ConserveVelocityParticleAffectorBase::executeSyncImpl(      ConserveVelocityParticleAffectorBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (ConserveFieldMask & whichField))
        _sfConserve.syncWith(pOther->_sfConserve);



}

void ConserveVelocityParticleAffectorBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ConserveVelocityParticleAffectorPtr>::_type("ConserveVelocityParticleAffectorPtr", "ParticleAffectorPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(ConserveVelocityParticleAffectorPtr, OSG_PARTICLESYSTEMLIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ConserveVelocityParticleAffectorPtr, OSG_PARTICLESYSTEMLIB_DLLTMPLMAPPING);


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: FCBaseTemplate_cpp.h,v 1.47 2006/03/17 17:03:19 pdaehne Exp $";
    static Char8 cvsid_hpp       [] = OSGCONSERVEVELOCITYPARTICLEAFFECTORBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGCONSERVEVELOCITYPARTICLEAFFECTORBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGCONSERVEVELOCITYPARTICLEAFFECTORFIELDS_HEADER_CVSID;
}

OSG_END_NAMESPACE

