/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMATERIALMAPKEYFIELDEDITORFIELDS_H_
#define _OSGMATERIALMAPKEYFIELDEDITORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribFieldContainerEditorDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class MaterialMapKeyFieldEditor;

OSG_GEN_CONTAINERPTR(MaterialMapKeyFieldEditor);

/*! \ingroup GrpContribFieldContainerEditorFieldTraits
    \ingroup GrpLibOSGContribFieldContainerEditor
 */
template <>
struct FieldTraits<MaterialMapKeyFieldEditor *> :
    public FieldTraitsFCPtrBase<MaterialMapKeyFieldEditor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<MaterialMapKeyFieldEditor *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBFIELDCONTAINEREDITOR_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFMaterialMapKeyFieldEditorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFMaterialMapKeyFieldEditorPtr"; }
};

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMaterialMapKeyFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMaterialMapKeyFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMaterialMapKeyFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMaterialMapKeyFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMaterialMapKeyFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMaterialMapKeyFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMaterialMapKeyFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialMapKeyFieldEditor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMaterialMapKeyFieldEditorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<MaterialMapKeyFieldEditor *,
                      RecordedRefCountPolicy  > SFRecMaterialMapKeyFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<MaterialMapKeyFieldEditor *,
                      UnrecordedRefCountPolicy> SFUnrecMaterialMapKeyFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<MaterialMapKeyFieldEditor *,
                      WeakRefCountPolicy      > SFWeakMaterialMapKeyFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<MaterialMapKeyFieldEditor *,
                      NoRefCountPolicy        > SFUncountedMaterialMapKeyFieldEditorPtr;


/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<MaterialMapKeyFieldEditor *,
                      RecordedRefCountPolicy  > MFRecMaterialMapKeyFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<MaterialMapKeyFieldEditor *,
                      UnrecordedRefCountPolicy> MFUnrecMaterialMapKeyFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<MaterialMapKeyFieldEditor *,
                      WeakRefCountPolicy      > MFWeakMaterialMapKeyFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<MaterialMapKeyFieldEditor *,
                      NoRefCountPolicy        > MFUncountedMaterialMapKeyFieldEditorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFRecMaterialMapKeyFieldEditorPtr : 
    public PointerSField<MaterialMapKeyFieldEditor *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFUnrecMaterialMapKeyFieldEditorPtr : 
    public PointerSField<MaterialMapKeyFieldEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFWeakMaterialMapKeyFieldEditorPtr :
    public PointerSField<MaterialMapKeyFieldEditor *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFUncountedMaterialMapKeyFieldEditorPtr :
    public PointerSField<MaterialMapKeyFieldEditor *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFRecMaterialMapKeyFieldEditorPtr :
    public PointerMField<MaterialMapKeyFieldEditor *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFUnrecMaterialMapKeyFieldEditorPtr :
    public PointerMField<MaterialMapKeyFieldEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFWeakMaterialMapKeyFieldEditorPtr :
    public PointerMField<MaterialMapKeyFieldEditor *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFUncountedMaterialMapKeyFieldEditorPtr :
    public PointerMField<MaterialMapKeyFieldEditor *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMATERIALMAPKEYFIELDEDITORFIELDS_H_ */
