/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com),  Behboud Kalantary         *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPHYSICSQUADTREESPACEFIELDS_H_
#define _OSGPHYSICSQUADTREESPACEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribPhysicsDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PhysicsQuadTreeSpace;

OSG_GEN_CONTAINERPTR(PhysicsQuadTreeSpace);

/*! \ingroup GrpContribPhysicsFieldTraits
    \ingroup GrpLibOSGContribPhysics
 */
template <>
struct FieldTraits<PhysicsQuadTreeSpace *> :
    public FieldTraitsFCPtrBase<PhysicsQuadTreeSpace *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PhysicsQuadTreeSpace *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBPHYSICS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPhysicsQuadTreeSpacePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPhysicsQuadTreeSpacePtr"; }
};

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPhysicsQuadTreeSpacePtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPhysicsQuadTreeSpacePtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPhysicsQuadTreeSpacePtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPhysicsQuadTreeSpacePtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPhysicsQuadTreeSpacePtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPhysicsQuadTreeSpacePtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPhysicsQuadTreeSpacePtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsQuadTreeSpace *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPhysicsQuadTreeSpacePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsQuadTreeSpace *,
                      RecordedRefCountPolicy  > SFRecPhysicsQuadTreeSpacePtr;
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsQuadTreeSpace *,
                      UnrecordedRefCountPolicy> SFUnrecPhysicsQuadTreeSpacePtr;
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsQuadTreeSpace *,
                      WeakRefCountPolicy      > SFWeakPhysicsQuadTreeSpacePtr;
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsQuadTreeSpace *,
                      NoRefCountPolicy        > SFUncountedPhysicsQuadTreeSpacePtr;


/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsQuadTreeSpace *,
                      RecordedRefCountPolicy  > MFRecPhysicsQuadTreeSpacePtr;
/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsQuadTreeSpace *,
                      UnrecordedRefCountPolicy> MFUnrecPhysicsQuadTreeSpacePtr;
/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsQuadTreeSpace *,
                      WeakRefCountPolicy      > MFWeakPhysicsQuadTreeSpacePtr;
/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsQuadTreeSpace *,
                      NoRefCountPolicy        > MFUncountedPhysicsQuadTreeSpacePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFRecPhysicsQuadTreeSpacePtr : 
    public PointerSField<PhysicsQuadTreeSpace *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFUnrecPhysicsQuadTreeSpacePtr : 
    public PointerSField<PhysicsQuadTreeSpace *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFWeakPhysicsQuadTreeSpacePtr :
    public PointerSField<PhysicsQuadTreeSpace *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFUncountedPhysicsQuadTreeSpacePtr :
    public PointerSField<PhysicsQuadTreeSpace *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFRecPhysicsQuadTreeSpacePtr :
    public PointerMField<PhysicsQuadTreeSpace *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFUnrecPhysicsQuadTreeSpacePtr :
    public PointerMField<PhysicsQuadTreeSpace *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFWeakPhysicsQuadTreeSpacePtr :
    public PointerMField<PhysicsQuadTreeSpace *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFUncountedPhysicsQuadTreeSpacePtr :
    public PointerMField<PhysicsQuadTreeSpace *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPHYSICSQUADTREESPACEFIELDS_H_ */
