/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox UserInterface                          *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala, Alden Peterson, Lee Zaniewski, Jonathan Flory    *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ArcUIDrawObject
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGARCUIDRAWOBJECTBASE_H_
#define _OSGARCUIDRAWOBJECTBASE_H_
#ifdef __sgi
#pragma once
#endif


#include <OpenSG/OSGConfig.h>
#include "OSGUserInterfaceDef.h"

#include <OpenSG/OSGBaseTypes.h>
#include <OpenSG/OSGRefPtr.h>
#include <OpenSG/OSGCoredNodePtr.h>

#include "OSGUIDrawObject.h" // Parent

#include <OpenSG/OSGPnt2fFields.h> // Center type
#include <OpenSG/OSGReal32Fields.h> // Width type
#include <OpenSG/OSGReal32Fields.h> // Height type
#include <OpenSG/OSGReal32Fields.h> // StartAngleRad type
#include <OpenSG/OSGReal32Fields.h> // EndAngleRad type
#include <OpenSG/OSGUInt16Fields.h> // SubDivisions type
#include <OpenSG/OSGColor4fFields.h> // Color type
#include <OpenSG/OSGReal32Fields.h> // LineWidth type
#include <OpenSG/OSGReal32Fields.h> // Opacity type

#include "OSGArcUIDrawObjectFields.h"

OSG_BEGIN_NAMESPACE

class ArcUIDrawObject;
class BinaryDataHandler;

//! \brief ArcUIDrawObject Base Class.

class OSG_USERINTERFACELIB_DLLMAPPING ArcUIDrawObjectBase : public UIDrawObject
{
  private:

    typedef UIDrawObject    Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    typedef ArcUIDrawObjectPtr  Ptr;

    enum
    {
        CenterFieldId        = Inherited::NextFieldId,
        WidthFieldId         = CenterFieldId        + 1,
        HeightFieldId        = WidthFieldId         + 1,
        StartAngleRadFieldId = HeightFieldId        + 1,
        EndAngleRadFieldId   = StartAngleRadFieldId + 1,
        SubDivisionsFieldId  = EndAngleRadFieldId   + 1,
        ColorFieldId         = SubDivisionsFieldId  + 1,
        LineWidthFieldId     = ColorFieldId         + 1,
        OpacityFieldId       = LineWidthFieldId     + 1,
        NextFieldId          = OpacityFieldId       + 1
    };

    static const OSG::BitVector CenterFieldMask;
    static const OSG::BitVector WidthFieldMask;
    static const OSG::BitVector HeightFieldMask;
    static const OSG::BitVector StartAngleRadFieldMask;
    static const OSG::BitVector EndAngleRadFieldMask;
    static const OSG::BitVector SubDivisionsFieldMask;
    static const OSG::BitVector ColorFieldMask;
    static const OSG::BitVector LineWidthFieldMask;
    static const OSG::BitVector OpacityFieldMask;


    static const OSG::BitVector MTInfluenceMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static        FieldContainerType &getClassType    (void); 
    static        UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

           SFPnt2f             *getSFCenter         (void);
           SFReal32            *getSFWidth          (void);
           SFReal32            *getSFHeight         (void);
           SFReal32            *getSFStartAngleRad  (void);
           SFReal32            *getSFEndAngleRad    (void);
           SFUInt16            *getSFSubDivisions   (void);
           SFColor4f           *getSFColor          (void);
           SFReal32            *getSFLineWidth      (void);
           SFReal32            *getSFOpacity        (void);

           Pnt2f               &getCenter         (void);
     const Pnt2f               &getCenter         (void) const;
           Real32              &getWidth          (void);
     const Real32              &getWidth          (void) const;
           Real32              &getHeight         (void);
     const Real32              &getHeight         (void) const;
           Real32              &getStartAngleRad  (void);
     const Real32              &getStartAngleRad  (void) const;
           Real32              &getEndAngleRad    (void);
     const Real32              &getEndAngleRad    (void) const;
           UInt16              &getSubDivisions   (void);
     const UInt16              &getSubDivisions   (void) const;
           Color4f             &getColor          (void);
     const Color4f             &getColor          (void) const;
           Real32              &getLineWidth      (void);
     const Real32              &getLineWidth      (void) const;
           Real32              &getOpacity        (void);
     const Real32              &getOpacity        (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

     void setCenter         ( const Pnt2f &value );
     void setWidth          ( const Real32 &value );
     void setHeight         ( const Real32 &value );
     void setStartAngleRad  ( const Real32 &value );
     void setEndAngleRad    ( const Real32 &value );
     void setSubDivisions   ( const UInt16 &value );
     void setColor          ( const Color4f &value );
     void setLineWidth      ( const Real32 &value );
     void setOpacity        ( const Real32 &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (const BitVector         &whichField);
    virtual void   copyToBin  (      BinaryDataHandler &pMem,
                               const BitVector         &whichField);
    virtual void   copyFromBin(      BinaryDataHandler &pMem,
                               const BitVector         &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  ArcUIDrawObjectPtr      create          (void); 
    static  ArcUIDrawObjectPtr      createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFPnt2f             _sfCenter;
    SFReal32            _sfWidth;
    SFReal32            _sfHeight;
    SFReal32            _sfStartAngleRad;
    SFReal32            _sfEndAngleRad;
    SFUInt16            _sfSubDivisions;
    SFColor4f           _sfColor;
    SFReal32            _sfLineWidth;
    SFReal32            _sfOpacity;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    ArcUIDrawObjectBase(void);
    ArcUIDrawObjectBase(const ArcUIDrawObjectBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~ArcUIDrawObjectBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#if !defined(OSG_FIXED_MFIELDSYNC)
    void executeSyncImpl(      ArcUIDrawObjectBase *pOther,
                         const BitVector         &whichField);

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField);
#else
    void executeSyncImpl(      ArcUIDrawObjectBase *pOther,
                         const BitVector         &whichField,
                         const SyncInfo          &sInfo     );

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField,
                               const SyncInfo          &sInfo);

    virtual void execBeginEdit     (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

            void execBeginEditImpl (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

    virtual void onDestroyAspect(UInt32 uiId, UInt32 uiAspect);
#endif

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const ArcUIDrawObjectBase &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef ArcUIDrawObjectBase *ArcUIDrawObjectBaseP;

typedef osgIF<ArcUIDrawObjectBase::isNodeCore,
              CoredNodePtr<ArcUIDrawObject>,
              FieldContainer::attempt_to_create_CoredNodePtr_on_non_NodeCore_FC
              >::_IRet ArcUIDrawObjectNodePtr;

typedef RefPtr<ArcUIDrawObjectPtr> ArcUIDrawObjectRefPtr;

OSG_END_NAMESPACE

#define OSGARCUIDRAWOBJECTBASE_HEADER_CVSID "@(#)$Id: FCBaseTemplate_h.h,v 1.40 2005/07/20 00:10:14 vossg Exp $"

#endif /* _OSGARCUIDRAWOBJECTBASE_H_ */
