/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox UserInterface                          *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala, Alden Peterson, Lee Zaniewski, Jonathan Flory    *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class List!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILELISTINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGListBase.h"
#include "OSGList.h"

#include <Util/OSGUIDefines.h>            // CellOrientation default header

OSG_BEGIN_NAMESPACE

const OSG::BitVector  ListBase::CellOrientationFieldMask = 
    (TypeTraits<BitVector>::One << ListBase::CellOrientationFieldId);

const OSG::BitVector  ListBase::CellMajorAxisLengthFieldMask = 
    (TypeTraits<BitVector>::One << ListBase::CellMajorAxisLengthFieldId);

const OSG::BitVector  ListBase::CellGeneratorFieldMask = 
    (TypeTraits<BitVector>::One << ListBase::CellGeneratorFieldId);

const OSG::BitVector  ListBase::AutoScrollToFocusedFieldMask = 
    (TypeTraits<BitVector>::One << ListBase::AutoScrollToFocusedFieldId);

const OSG::BitVector ListBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var UInt32          ListBase::_sfCellOrientation
    
*/
/*! \var UInt32          ListBase::_sfCellMajorAxisLength
    
*/
/*! \var ComponentGeneratorPtr ListBase::_sfCellGenerator
    
*/
/*! \var bool            ListBase::_sfAutoScrollToFocused
    
*/

//! List description

FieldDescription *ListBase::_desc[] = 
{
    new FieldDescription(SFUInt32::getClassType(), 
                     "CellOrientation", 
                     CellOrientationFieldId, CellOrientationFieldMask,
                     false,
                     (FieldAccessMethod) &ListBase::getSFCellOrientation),
    new FieldDescription(SFUInt32::getClassType(), 
                     "CellMajorAxisLength", 
                     CellMajorAxisLengthFieldId, CellMajorAxisLengthFieldMask,
                     false,
                     (FieldAccessMethod) &ListBase::getSFCellMajorAxisLength),
    new FieldDescription(SFComponentGeneratorPtr::getClassType(), 
                     "CellGenerator", 
                     CellGeneratorFieldId, CellGeneratorFieldMask,
                     false,
                     (FieldAccessMethod) &ListBase::getSFCellGenerator),
    new FieldDescription(SFBool::getClassType(), 
                     "AutoScrollToFocused", 
                     AutoScrollToFocusedFieldId, AutoScrollToFocusedFieldMask,
                     false,
                     (FieldAccessMethod) &ListBase::getSFAutoScrollToFocused)
};


FieldContainerType ListBase::_type(
    "List",
    "Container",
    NULL,
    (PrototypeCreateF) &ListBase::createEmpty,
    List::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(ListBase, ListPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &ListBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ListBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr ListBase::shallowCopy(void) const 
{ 
    ListPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const List *>(this)); 

    return returnValue; 
}

UInt32 ListBase::getContainerSize(void) const 
{ 
    return sizeof(List); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void ListBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((ListBase *) &other, whichField);
}
#else
void ListBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((ListBase *) &other, whichField, sInfo);
}
void ListBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void ListBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

ListBase::ListBase(void) :
    _sfCellOrientation        (UInt32(VERTICAL_ALIGNMENT)), 
    _sfCellMajorAxisLength    (UInt32(50)), 
    _sfCellGenerator          (ComponentGeneratorPtr(NullFC)), 
    _sfAutoScrollToFocused    (bool(true)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

ListBase::ListBase(const ListBase &source) :
    _sfCellOrientation        (source._sfCellOrientation        ), 
    _sfCellMajorAxisLength    (source._sfCellMajorAxisLength    ), 
    _sfCellGenerator          (source._sfCellGenerator          ), 
    _sfAutoScrollToFocused    (source._sfAutoScrollToFocused    ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

ListBase::~ListBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 ListBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (CellOrientationFieldMask & whichField))
    {
        returnValue += _sfCellOrientation.getBinSize();
    }

    if(FieldBits::NoField != (CellMajorAxisLengthFieldMask & whichField))
    {
        returnValue += _sfCellMajorAxisLength.getBinSize();
    }

    if(FieldBits::NoField != (CellGeneratorFieldMask & whichField))
    {
        returnValue += _sfCellGenerator.getBinSize();
    }

    if(FieldBits::NoField != (AutoScrollToFocusedFieldMask & whichField))
    {
        returnValue += _sfAutoScrollToFocused.getBinSize();
    }


    return returnValue;
}

void ListBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (CellOrientationFieldMask & whichField))
    {
        _sfCellOrientation.copyToBin(pMem);
    }

    if(FieldBits::NoField != (CellMajorAxisLengthFieldMask & whichField))
    {
        _sfCellMajorAxisLength.copyToBin(pMem);
    }

    if(FieldBits::NoField != (CellGeneratorFieldMask & whichField))
    {
        _sfCellGenerator.copyToBin(pMem);
    }

    if(FieldBits::NoField != (AutoScrollToFocusedFieldMask & whichField))
    {
        _sfAutoScrollToFocused.copyToBin(pMem);
    }


}

void ListBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (CellOrientationFieldMask & whichField))
    {
        _sfCellOrientation.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (CellMajorAxisLengthFieldMask & whichField))
    {
        _sfCellMajorAxisLength.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (CellGeneratorFieldMask & whichField))
    {
        _sfCellGenerator.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (AutoScrollToFocusedFieldMask & whichField))
    {
        _sfAutoScrollToFocused.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void ListBase::executeSyncImpl(      ListBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (CellOrientationFieldMask & whichField))
        _sfCellOrientation.syncWith(pOther->_sfCellOrientation);

    if(FieldBits::NoField != (CellMajorAxisLengthFieldMask & whichField))
        _sfCellMajorAxisLength.syncWith(pOther->_sfCellMajorAxisLength);

    if(FieldBits::NoField != (CellGeneratorFieldMask & whichField))
        _sfCellGenerator.syncWith(pOther->_sfCellGenerator);

    if(FieldBits::NoField != (AutoScrollToFocusedFieldMask & whichField))
        _sfAutoScrollToFocused.syncWith(pOther->_sfAutoScrollToFocused);


}
#else
void ListBase::executeSyncImpl(      ListBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (CellOrientationFieldMask & whichField))
        _sfCellOrientation.syncWith(pOther->_sfCellOrientation);

    if(FieldBits::NoField != (CellMajorAxisLengthFieldMask & whichField))
        _sfCellMajorAxisLength.syncWith(pOther->_sfCellMajorAxisLength);

    if(FieldBits::NoField != (CellGeneratorFieldMask & whichField))
        _sfCellGenerator.syncWith(pOther->_sfCellGenerator);

    if(FieldBits::NoField != (AutoScrollToFocusedFieldMask & whichField))
        _sfAutoScrollToFocused.syncWith(pOther->_sfAutoScrollToFocused);



}

void ListBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ListPtr>::_type("ListPtr", "ContainerPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(ListPtr, OSG_USERINTERFACELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ListPtr, OSG_USERINTERFACELIB_DLLTMPLMAPPING);


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: FCBaseTemplate_cpp.h,v 1.47 2006/03/17 17:03:19 pdaehne Exp $";
    static Char8 cvsid_hpp       [] = OSGLISTBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGLISTBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGLISTFIELDS_HEADER_CVSID;
}

OSG_END_NAMESPACE

