/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox UserInterface                          *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *                          Authors: David Kabala                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TableColumnModelEvent!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILETABLECOLUMNMODELEVENTINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGTableColumnModelEventBase.h"
#include "OSGTableColumnModelEvent.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  TableColumnModelEventBase::FromIndexFieldMask = 
    (TypeTraits<BitVector>::One << TableColumnModelEventBase::FromIndexFieldId);

const OSG::BitVector  TableColumnModelEventBase::ToIndexFieldMask = 
    (TypeTraits<BitVector>::One << TableColumnModelEventBase::ToIndexFieldId);

const OSG::BitVector TableColumnModelEventBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var UInt32          TableColumnModelEventBase::_sfFromIndex
    
*/
/*! \var UInt32          TableColumnModelEventBase::_sfToIndex
    
*/

//! TableColumnModelEvent description

FieldDescription *TableColumnModelEventBase::_desc[] = 
{
    new FieldDescription(SFUInt32::getClassType(), 
                     "FromIndex", 
                     FromIndexFieldId, FromIndexFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&TableColumnModelEventBase::editSFFromIndex)),
    new FieldDescription(SFUInt32::getClassType(), 
                     "ToIndex", 
                     ToIndexFieldId, ToIndexFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&TableColumnModelEventBase::editSFToIndex))
};


FieldContainerType TableColumnModelEventBase::_type(
    "TableColumnModelEvent",
    "Event",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&TableColumnModelEventBase::createEmpty),
    TableColumnModelEvent::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(TableColumnModelEventBase, TableColumnModelEventPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &TableColumnModelEventBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &TableColumnModelEventBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr TableColumnModelEventBase::shallowCopy(void) const 
{ 
    TableColumnModelEventPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const TableColumnModelEvent *>(this)); 

    return returnValue; 
}

UInt32 TableColumnModelEventBase::getContainerSize(void) const 
{ 
    return sizeof(TableColumnModelEvent); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void TableColumnModelEventBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<TableColumnModelEventBase *>(&other),
                          whichField);
}
#else
void TableColumnModelEventBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((TableColumnModelEventBase *) &other, whichField, sInfo);
}
void TableColumnModelEventBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void TableColumnModelEventBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

TableColumnModelEventBase::TableColumnModelEventBase(void) :
    _sfFromIndex              (UInt32(0)), 
    _sfToIndex                (UInt32(0)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

TableColumnModelEventBase::TableColumnModelEventBase(const TableColumnModelEventBase &source) :
    _sfFromIndex              (source._sfFromIndex              ), 
    _sfToIndex                (source._sfToIndex                ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

TableColumnModelEventBase::~TableColumnModelEventBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 TableColumnModelEventBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (FromIndexFieldMask & whichField))
    {
        returnValue += _sfFromIndex.getBinSize();
    }

    if(FieldBits::NoField != (ToIndexFieldMask & whichField))
    {
        returnValue += _sfToIndex.getBinSize();
    }


    return returnValue;
}

void TableColumnModelEventBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (FromIndexFieldMask & whichField))
    {
        _sfFromIndex.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ToIndexFieldMask & whichField))
    {
        _sfToIndex.copyToBin(pMem);
    }


}

void TableColumnModelEventBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (FromIndexFieldMask & whichField))
    {
        _sfFromIndex.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ToIndexFieldMask & whichField))
    {
        _sfToIndex.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void TableColumnModelEventBase::executeSyncImpl(      TableColumnModelEventBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (FromIndexFieldMask & whichField))
        _sfFromIndex.syncWith(pOther->_sfFromIndex);

    if(FieldBits::NoField != (ToIndexFieldMask & whichField))
        _sfToIndex.syncWith(pOther->_sfToIndex);


}
#else
void TableColumnModelEventBase::executeSyncImpl(      TableColumnModelEventBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (FromIndexFieldMask & whichField))
        _sfFromIndex.syncWith(pOther->_sfFromIndex);

    if(FieldBits::NoField != (ToIndexFieldMask & whichField))
        _sfToIndex.syncWith(pOther->_sfToIndex);



}

void TableColumnModelEventBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<TableColumnModelEventPtr>::_type("TableColumnModelEventPtr", "EventPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(TableColumnModelEventPtr, OSG_USERINTERFACELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

