
MESSAGE(STATUS "Prepare OSGContribSound")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake")

INCLUDE(ConfigurePackages.OSGContribSound)

OSG_CONFIGURE_FMOD()

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine _OSG_USE_FMOD_ 1")

IF(UNIX)
  OSG_ADD_OPT(FMOD_LIBRARIES)
  OSG_ADD_OPT(FMOD_INCLUDE_DIR)
ENDIF(UNIX)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/FindFmod.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/ConfigurePackages.OSGContribSound.cmake"
        DESTINATION share/OpenSG/cmake)
