/*---------------------------------------------------------------------------*\
 *                       OpenSG ToolBox Animation                            *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *                          Authors: David Kabala                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class AnimationActivity!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEANIMATIONACTIVITYINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGAnimationActivityBase.h"
#include "OSGAnimationActivity.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  AnimationActivityBase::AnimationFieldMask = 
    (TypeTraits<BitVector>::One << AnimationActivityBase::AnimationFieldId);

const OSG::BitVector  AnimationActivityBase::ActivityTypeFieldMask = 
    (TypeTraits<BitVector>::One << AnimationActivityBase::ActivityTypeFieldId);

const OSG::BitVector AnimationActivityBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var AnimationPtr    AnimationActivityBase::_sfAnimation
    
*/
/*! \var UInt8           AnimationActivityBase::_sfActivityType
    
*/

//! AnimationActivity description

FieldDescription *AnimationActivityBase::_desc[] = 
{
    new FieldDescription(SFAnimationPtr::getClassType(), 
                     "Animation", 
                     AnimationFieldId, AnimationFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&AnimationActivityBase::editSFAnimation)),
    new FieldDescription(SFUInt8::getClassType(), 
                     "ActivityType", 
                     ActivityTypeFieldId, ActivityTypeFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&AnimationActivityBase::editSFActivityType))
};


FieldContainerType AnimationActivityBase::_type(
    "AnimationActivity",
    "Activity",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&AnimationActivityBase::createEmpty),
    AnimationActivity::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(AnimationActivityBase, AnimationActivityPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &AnimationActivityBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &AnimationActivityBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr AnimationActivityBase::shallowCopy(void) const 
{ 
    AnimationActivityPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const AnimationActivity *>(this)); 

    return returnValue; 
}

UInt32 AnimationActivityBase::getContainerSize(void) const 
{ 
    return sizeof(AnimationActivity); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void AnimationActivityBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<AnimationActivityBase *>(&other),
                          whichField);
}
#else
void AnimationActivityBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((AnimationActivityBase *) &other, whichField, sInfo);
}
void AnimationActivityBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void AnimationActivityBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

AnimationActivityBase::AnimationActivityBase(void) :
    _sfAnimation              (AnimationPtr(NullFC)), 
    _sfActivityType           (UInt8(AnimationActivity::ANIMATION_START)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

AnimationActivityBase::AnimationActivityBase(const AnimationActivityBase &source) :
    _sfAnimation              (source._sfAnimation              ), 
    _sfActivityType           (source._sfActivityType           ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

AnimationActivityBase::~AnimationActivityBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 AnimationActivityBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (AnimationFieldMask & whichField))
    {
        returnValue += _sfAnimation.getBinSize();
    }

    if(FieldBits::NoField != (ActivityTypeFieldMask & whichField))
    {
        returnValue += _sfActivityType.getBinSize();
    }


    return returnValue;
}

void AnimationActivityBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (AnimationFieldMask & whichField))
    {
        _sfAnimation.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ActivityTypeFieldMask & whichField))
    {
        _sfActivityType.copyToBin(pMem);
    }


}

void AnimationActivityBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (AnimationFieldMask & whichField))
    {
        _sfAnimation.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ActivityTypeFieldMask & whichField))
    {
        _sfActivityType.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void AnimationActivityBase::executeSyncImpl(      AnimationActivityBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (AnimationFieldMask & whichField))
        _sfAnimation.syncWith(pOther->_sfAnimation);

    if(FieldBits::NoField != (ActivityTypeFieldMask & whichField))
        _sfActivityType.syncWith(pOther->_sfActivityType);


}
#else
void AnimationActivityBase::executeSyncImpl(      AnimationActivityBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (AnimationFieldMask & whichField))
        _sfAnimation.syncWith(pOther->_sfAnimation);

    if(FieldBits::NoField != (ActivityTypeFieldMask & whichField))
        _sfActivityType.syncWith(pOther->_sfActivityType);



}

void AnimationActivityBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<AnimationActivityPtr>::_type("AnimationActivityPtr", "ActivityPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(AnimationActivityPtr, OSG_ANIMATIONLIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(AnimationActivityPtr, OSG_ANIMATIONLIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

