/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ListSelectionEventDetails!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


OSG_BEGIN_NAMESPACE


//! access the type of the class
inline
OSG::FieldContainerType &ListSelectionEventDetailsBase::getClassType(void)
{
    return _type;
}

//! access the numerical type of the class
inline
OSG::UInt32 ListSelectionEventDetailsBase::getClassTypeId(void)
{
    return _type.getId();
}

inline
OSG::UInt16 ListSelectionEventDetailsBase::getClassGroupId(void)
{
    return _type.getGroupId();
}

/*------------------------------ get -----------------------------------*/

//! Get the value of the ListSelectionEventDetails::_sfFirstIndex field.

inline
Int32 &ListSelectionEventDetailsBase::editFirstIndex(void)
{
    editSField(FirstIndexFieldMask);

    return _sfFirstIndex.getValue();
}

//! Get the value of the ListSelectionEventDetails::_sfFirstIndex field.
inline
      Int32  ListSelectionEventDetailsBase::getFirstIndex(void) const
{
    return _sfFirstIndex.getValue();
}

//! Set the value of the ListSelectionEventDetails::_sfFirstIndex field.
inline
void ListSelectionEventDetailsBase::setFirstIndex(const Int32 value)
{
    editSField(FirstIndexFieldMask);

    _sfFirstIndex.setValue(value);
}
//! Get the value of the ListSelectionEventDetails::_sfLastIndex field.

inline
Int32 &ListSelectionEventDetailsBase::editLastIndex(void)
{
    editSField(LastIndexFieldMask);

    return _sfLastIndex.getValue();
}

//! Get the value of the ListSelectionEventDetails::_sfLastIndex field.
inline
      Int32  ListSelectionEventDetailsBase::getLastIndex(void) const
{
    return _sfLastIndex.getValue();
}

//! Set the value of the ListSelectionEventDetails::_sfLastIndex field.
inline
void ListSelectionEventDetailsBase::setLastIndex(const Int32 value)
{
    editSField(LastIndexFieldMask);

    _sfLastIndex.setValue(value);
}


#ifdef OSG_MT_CPTR_ASPECT
inline
void ListSelectionEventDetailsBase::execSync (      ListSelectionEventDetailsBase *pFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    Inherited::execSync(pFrom, whichField, oOffsets, syncMode, uiSyncInfo);

    if(FieldBits::NoField != (FirstIndexFieldMask & whichField))
        _sfFirstIndex.syncWith(pFrom->_sfFirstIndex);

    if(FieldBits::NoField != (LastIndexFieldMask & whichField))
        _sfLastIndex.syncWith(pFrom->_sfLastIndex);
}
#endif


inline
const Char8 *ListSelectionEventDetailsBase::getClassname(void)
{
    return "ListSelectionEventDetails";
}
OSG_GEN_CONTAINERPTR(ListSelectionEventDetails);

OSG_END_NAMESPACE

