MACRO(OSG_CONFIGURE_FMOD)
    OSG_OPTION(OSG_ENABLE_SOUND_FMOD "" OFF)
    
    IF(OSG_ENABLE_SOUND_FMOD)

        IF(OSG_USE_OSGSUPPORT_LIBS AND WIN32)
    
            IF(EXISTS ${OSG_SUPPORT_ROOT}/inc/fmod.h)
                SET(FMOD_INCLUDE_DIR ${OSG_SUPPORT_ROOT}/include CACHE PATH "" FORCE)
            ENDIF()
    
            IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osgfmodex.lib)
                SET(FMOD_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/osgfmodex.lib)
            ENDIF()
            IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osggdalD.lib)
                SET(FMOD_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/osgfmodexD.lib)
            ENDIF()
    
            IF(FMOD_INCLUDE_DIR)
              IF(FMOD_LIBRARY_DEBUG OR FMOD_LIBRARY_RELEASE)
                SET(FMOD_FOUND TRUE)
              ENDIF()
            ENDIF()
    
            IF(FMOD_FOUND)
              OSG_ADD_IMPORT_LIB(OSG_FMOD_TARGETS FMOD_LIBRARY)
              SET(FMOD_LIBRARIES ${OSG_FMOD_TARGETS} CACHE STRING "" FORCE)
            ENDIF(FMOD_FOUND)
    
        ENDIF(OSG_USE_OSGSUPPORT_LIBS AND WIN32)
    
        IF(NOT OSG_USE_OSGSUPPORT_LIBS OR NOT FMOD_FOUND)
            OSG_FIND_PACKAGE(Fmod)
        ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS OR NOT FMOD_FOUND)
    
        IF(FMOD_FOUND)
            OSG_SET(OSG_WITH_FMOD 1)
        ENDIF(FMOD_FOUND)
        
    ELSE(OSG_ENABLE_SOUND_FMOD)
        OSG_SET(OSG_WITH_FMOD 0)
    ENDIF(OSG_ENABLE_SOUND_FMOD)
ENDMACRO(OSG_CONFIGURE_FMOD)

