
MESSAGE(STATUS "Prepare OSGContribPhysics")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake")

INCLUDE(ConfigurePackages.OSGContribPhysics)

OSG_CONFIGURE_ODE()

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_ODE 1")

IF(UNIX)
  OSG_ADD_OPT(ODE_LIBRARIES)
  OSG_ADD_OPT(ODE_INCLUDE_DIR)
ENDIF(UNIX)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/FindODE.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/ConfigurePackages.OSGContribPhysics.cmake"
        DESTINATION share/OpenSG/cmake)
