/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOMPOUNDLAYOUTSPRINGFIELDS_H_
#define _OSGCOMPOUNDLAYOUTSPRINGFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class CompoundLayoutSpring;

OSG_GEN_CONTAINERPTR(CompoundLayoutSpring);

/*! \ingroup GrpContribUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribUserInterface
 */
template <>
struct FieldTraits<CompoundLayoutSpring *> :
    public FieldTraitsFCPtrBase<CompoundLayoutSpring *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<CompoundLayoutSpring *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFCompoundLayoutSpringPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFCompoundLayoutSpringPtr"; }
};

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecCompoundLayoutSpringPtr"; 
}

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecCompoundLayoutSpringPtr"; 
}

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakCompoundLayoutSpringPtr"; 
}

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdCompoundLayoutSpringPtr"; 
}

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecCompoundLayoutSpringPtr"; 
}

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecCompoundLayoutSpringPtr"; 
}

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakCompoundLayoutSpringPtr"; 
}

template<> inline
const Char8 *FieldTraits<CompoundLayoutSpring *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdCompoundLayoutSpringPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<CompoundLayoutSpring *,
                      RecordedRefCountPolicy  > SFRecCompoundLayoutSpringPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<CompoundLayoutSpring *,
                      UnrecordedRefCountPolicy> SFUnrecCompoundLayoutSpringPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<CompoundLayoutSpring *,
                      WeakRefCountPolicy      > SFWeakCompoundLayoutSpringPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<CompoundLayoutSpring *,
                      NoRefCountPolicy        > SFUncountedCompoundLayoutSpringPtr;


/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<CompoundLayoutSpring *,
                      RecordedRefCountPolicy  > MFRecCompoundLayoutSpringPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<CompoundLayoutSpring *,
                      UnrecordedRefCountPolicy> MFUnrecCompoundLayoutSpringPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<CompoundLayoutSpring *,
                      WeakRefCountPolicy      > MFWeakCompoundLayoutSpringPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<CompoundLayoutSpring *,
                      NoRefCountPolicy        > MFUncountedCompoundLayoutSpringPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFRecCompoundLayoutSpringPtr : 
    public PointerSField<CompoundLayoutSpring *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUnrecCompoundLayoutSpringPtr : 
    public PointerSField<CompoundLayoutSpring *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFWeakCompoundLayoutSpringPtr :
    public PointerSField<CompoundLayoutSpring *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUncountedCompoundLayoutSpringPtr :
    public PointerSField<CompoundLayoutSpring *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFRecCompoundLayoutSpringPtr :
    public PointerMField<CompoundLayoutSpring *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUnrecCompoundLayoutSpringPtr :
    public PointerMField<CompoundLayoutSpring *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFWeakCompoundLayoutSpringPtr :
    public PointerMField<CompoundLayoutSpring *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUncountedCompoundLayoutSpringPtr :
    public PointerMField<CompoundLayoutSpring *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOMPOUNDLAYOUTSPRINGFIELDS_H_ */
