
MESSAGE(STATUS "Prepare OSGContribLuaToolbox")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/../../src/CMake")

INCLUDE(ConfigurePackages.OSGContribLua)

OSG_CONFIGURE_LUA()

