MACRO(OSG_CONFIGURE_LUA)

    IF(OSG_USE_OSGSUPPORT_LIBS AND WIN32)

        IF(EXISTS ${OSG_SUPPORT_ROOT}/include/lua.h)
            SET(LUA_INCLUDE_DIR ${OSG_SUPPORT_ROOT}/include CACHE PATH "" FORCE)
        ENDIF()

        IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osglua5.1.lib)
            SET(LUA_LIBRARY_RELEASE ${OSG_SUPPORT_ROOT}/lib/osglua.lib)
        ENDIF()
        IF(EXISTS ${OSG_SUPPORT_ROOT}/lib/osglua5.1D.lib)
            SET(LUA_LIBRARY_DEBUG ${OSG_SUPPORT_ROOT}/lib/oslua5.1D.lib)
        ENDIF()

        IF(LUA_INCLUDE_DIR)
          IF(LUA_LIBRARY_DEBUG OR LUA_LIBRARY_RELEASE)
            SET(LUA_FOUND TRUE)
          ENDIF()
        ENDIF()

        IF(LUA_FOUND)
          OSG_ADD_IMPORT_LIB(OSG_LUA_TARGETS LUA_LIBRARY)
          SET(LUA_LIBRARIES ${OSG_LUA_TARGETS} CACHE STRING "" FORCE)
        ENDIF(LUA_FOUND)

    ENDIF(OSG_USE_OSGSUPPORT_LIBS AND WIN32)

    IF(NOT OSG_USE_OSGSUPPORT_LIBS OR NOT LUA_FOUND)
        OSG_FIND_PACKAGE(LUA)
    ENDIF(NOT OSG_USE_OSGSUPPORT_LIBS OR NOT LUA_FOUND)

    IF(FMOD_FOUND)
        OSG_SET(OSG_WITH_LUA 1)
    ENDIF(FMOD_FOUND)
ENDMACRO(OSG_CONFIGURE_LUA)
