###

LIB_NAME = OSGPhysics
LIB_INCLUDE_DIR_NAME = Physics

srcdir = ../../../src
installdir = ../../../../Builds/Linux
commondir = ../../../../Builds/Common
VPATH = $(srcdir)/:$(srcdir)/Physics:$(srcdir)/Physics/Actors:$(srcdir)/Physics/Integrations:$(srcdir)/Physics/Objects:$(srcdir)/Physics/Objects/Attributes:$(srcdir)/Physics/Systems:$(srcdir)/Physics/Systems/Forces:


#.SUFFIX = .o .o

EXTRA_CCFLAGS = -I$(srcdir)

OBJECTS = OSGPhysicsActor.o \
	OSGPhysicsActorBase.o \
	OSGEulerIntegration.o \
	OSGEulerIntegrationBase.o \
	OSGImprovedEulerIntegration.o \
	OSGImprovedEulerIntegrationBase.o \
	OSGIntegration.o \
	OSGIntegrationBase.o \
	OSGRungeKuttaIntegration.o \
	OSGRungeKuttaIntegrationBase.o \
	OSGFluid.o \
	OSGFluidBase.o \
	OSGPhysicsCore.o \
	OSGPhysicsCoreBase.o \
	OSGSurface.o \
	OSGSurfaceBase.o \
	OSGCollidableAttribute.o \
	OSGCollidableAttributeBase.o \
	OSGDragGeometricAttribute.o \
	OSGDragGeometricAttributeBase.o \
	OSGImovableAttribute.o \
	OSGImovableAttributeBase.o \
	OSGInertiaAttribute.o \
	OSGInertiaAttributeBase.o \
	OSGLinearPositionalAttribute.o \
	OSGLinearPositionalAttributeBase.o \
	OSGMassAttribute.o \
	OSGMassAttributeBase.o \
	OSGPhysicsObjectAttribute.o \
	OSGPhysicsObjectAttributeBase.o \
	OSGRotationalAttribute.o \
	OSGRotationalAttributeBase.o \
	OSGRotationalDragGeometricAttribute.o \
	OSGRotationalDragGeometricAttributeBase.o \
	OSGVolumeAttribute.o \
	OSGVolumeAttributeBase.o \
	OSGForceSystem.o \
	OSGForceSystemBase.o \
	OSGPhysicsSystem.o \
	OSGPhysicsSystemBase.o \
	OSGBoyancyForce.o \
	OSGBoyancyForceBase.o \
	OSGDefinedForce.o \
	OSGDefinedForceBase.o \
	OSGForce.o \
	OSGForceBase.o \
	OSGGravitationalForce.o \
	OSGGravitationalForceBase.o \
	OSGKineticSurfaceFrictionForce.o \
	OSGKineticSurfaceFrictionForceBase.o \
	OSGNormalForce.o \
	OSGNormalForceBase.o \
	OSGRocketForce.o \
	OSGRocketForceBase.o \
	OSGSimpleDragForce.o \
	OSGSimpleDragForceBase.o \
	OSGSimpleRotationalDragForce.o \
	OSGSimpleRotationalDragForceBase.o \
	OSGSpringForce.o \
	OSGSpringForceBase.o \
	OSGStaticSurfaceFrictionForce.o \
	OSGStaticSurfaceFrictionForceBase.o \
	OSGSurfaceFrictionForce.o \
	OSGSurfaceFrictionForceBase.o
        
        
include $(commondir)/CommonMake.mk
