/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGABSTRACTMUTABLECOMBOBOXMODELFIELDS_H_
#define _OSGABSTRACTMUTABLECOMBOBOXMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class AbstractMutableComboBoxModel;

OSG_GEN_CONTAINERPTR(AbstractMutableComboBoxModel);

/*! \ingroup GrpContribUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribUserInterface
 */
template <>
struct FieldTraits<AbstractMutableComboBoxModel *> :
    public FieldTraitsFCPtrBase<AbstractMutableComboBoxModel *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<AbstractMutableComboBoxModel *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFAbstractMutableComboBoxModelPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFAbstractMutableComboBoxModelPtr"; }
};

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAbstractMutableComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAbstractMutableComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAbstractMutableComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAbstractMutableComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAbstractMutableComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAbstractMutableComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAbstractMutableComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractMutableComboBoxModel *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAbstractMutableComboBoxModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<AbstractMutableComboBoxModel *,
                      RecordedRefCountPolicy  > SFRecAbstractMutableComboBoxModelPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<AbstractMutableComboBoxModel *,
                      UnrecordedRefCountPolicy> SFUnrecAbstractMutableComboBoxModelPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<AbstractMutableComboBoxModel *,
                      WeakRefCountPolicy      > SFWeakAbstractMutableComboBoxModelPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<AbstractMutableComboBoxModel *,
                      NoRefCountPolicy        > SFUncountedAbstractMutableComboBoxModelPtr;


/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<AbstractMutableComboBoxModel *,
                      RecordedRefCountPolicy  > MFRecAbstractMutableComboBoxModelPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<AbstractMutableComboBoxModel *,
                      UnrecordedRefCountPolicy> MFUnrecAbstractMutableComboBoxModelPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<AbstractMutableComboBoxModel *,
                      WeakRefCountPolicy      > MFWeakAbstractMutableComboBoxModelPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<AbstractMutableComboBoxModel *,
                      NoRefCountPolicy        > MFUncountedAbstractMutableComboBoxModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFRecAbstractMutableComboBoxModelPtr : 
    public PointerSField<AbstractMutableComboBoxModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUnrecAbstractMutableComboBoxModelPtr : 
    public PointerSField<AbstractMutableComboBoxModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFWeakAbstractMutableComboBoxModelPtr :
    public PointerSField<AbstractMutableComboBoxModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUncountedAbstractMutableComboBoxModelPtr :
    public PointerSField<AbstractMutableComboBoxModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFRecAbstractMutableComboBoxModelPtr :
    public PointerMField<AbstractMutableComboBoxModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUnrecAbstractMutableComboBoxModelPtr :
    public PointerMField<AbstractMutableComboBoxModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFWeakAbstractMutableComboBoxModelPtr :
    public PointerMField<AbstractMutableComboBoxModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUncountedAbstractMutableComboBoxModelPtr :
    public PointerMField<AbstractMutableComboBoxModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGABSTRACTMUTABLECOMBOBOXMODELFIELDS_H_ */
