/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Spinner!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

OSG_BEGIN_NAMESPACE


//! access the type of the class
inline
OSG::FieldContainerType &SpinnerBase::getClassType(void)
{
    return _type;
}

//! access the numerical type of the class
inline
OSG::UInt32 SpinnerBase::getClassTypeId(void)
{
    return _type.getId();
}

inline
OSG::UInt16 SpinnerBase::getClassGroupId(void)
{
    return _type.getGroupId();
}

/*------------------------------ get -----------------------------------*/


//! Get the value of the Spinner::_sfNextButton field.
inline
Button * SpinnerBase::getNextButton(void) const
{
    return _sfNextButton.getValue();
}

//! Set the value of the Spinner::_sfNextButton field.
inline
void SpinnerBase::setNextButton(Button * const value)
{
    editSField(NextButtonFieldMask);

    _sfNextButton.setValue(value);
}

//! Get the value of the Spinner::_sfPreviousButton field.
inline
Button * SpinnerBase::getPreviousButton(void) const
{
    return _sfPreviousButton.getValue();
}

//! Set the value of the Spinner::_sfPreviousButton field.
inline
void SpinnerBase::setPreviousButton(Button * const value)
{
    editSField(PreviousButtonFieldMask);

    _sfPreviousButton.setValue(value);
}

//! Get the value of the Spinner::_sfEditor field.
inline
Component * SpinnerBase::getEditor(void) const
{
    return _sfEditor.getValue();
}

//! Set the value of the Spinner::_sfEditor field.
inline
void SpinnerBase::setEditor(Component * const value)
{
    editSField(EditorFieldMask);

    _sfEditor.setValue(value);
}
//! Get the value of the Spinner::_sfOrientation field.

inline
UInt32 &SpinnerBase::editOrientation(void)
{
    editSField(OrientationFieldMask);

    return _sfOrientation.getValue();
}

//! Get the value of the Spinner::_sfOrientation field.
inline
      UInt32  SpinnerBase::getOrientation(void) const
{
    return _sfOrientation.getValue();
}

//! Set the value of the Spinner::_sfOrientation field.
inline
void SpinnerBase::setOrientation(const UInt32 value)
{
    editSField(OrientationFieldMask);

    _sfOrientation.setValue(value);
}
//! Get the value of the Spinner::_sfEditorToButtonOffset field.

inline
UInt32 &SpinnerBase::editEditorToButtonOffset(void)
{
    editSField(EditorToButtonOffsetFieldMask);

    return _sfEditorToButtonOffset.getValue();
}

//! Get the value of the Spinner::_sfEditorToButtonOffset field.
inline
      UInt32  SpinnerBase::getEditorToButtonOffset(void) const
{
    return _sfEditorToButtonOffset.getValue();
}

//! Set the value of the Spinner::_sfEditorToButtonOffset field.
inline
void SpinnerBase::setEditorToButtonOffset(const UInt32 value)
{
    editSField(EditorToButtonOffsetFieldMask);

    _sfEditorToButtonOffset.setValue(value);
}


#ifdef OSG_MT_CPTR_ASPECT
inline
void SpinnerBase::execSync (      SpinnerBase *pFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    Inherited::execSync(pFrom, whichField, oOffsets, syncMode, uiSyncInfo);

    if(FieldBits::NoField != (NextButtonFieldMask & whichField))
        _sfNextButton.syncWith(pFrom->_sfNextButton);

    if(FieldBits::NoField != (PreviousButtonFieldMask & whichField))
        _sfPreviousButton.syncWith(pFrom->_sfPreviousButton);

    if(FieldBits::NoField != (EditorFieldMask & whichField))
        _sfEditor.syncWith(pFrom->_sfEditor);

    if(FieldBits::NoField != (OrientationFieldMask & whichField))
        _sfOrientation.syncWith(pFrom->_sfOrientation);

    if(FieldBits::NoField != (EditorToButtonOffsetFieldMask & whichField))
        _sfEditorToButtonOffset.syncWith(pFrom->_sfEditorToButtonOffset);
}
#endif


inline
const Char8 *SpinnerBase::getClassname(void)
{
    return "Spinner";
}
OSG_GEN_CONTAINERPTR(Spinner);

OSG_END_NAMESPACE

