/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2002 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FModSoundChannel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEFMODSOUNDCHANNELINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGFModSoundChannelBase.h"
#include "OSGFModSoundChannel.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector FModSoundChannelBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 



FieldContainerType FModSoundChannelBase::_type(
    "FModSoundChannel",
    "SoundChannel",
    NULL,
    (PrototypeCreateF) &FModSoundChannelBase::createEmpty,
    FModSoundChannel::initMethod,
    NULL,
    0);

//OSG_FIELD_CONTAINER_DEF(FModSoundChannelBase, FModSoundChannelPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &FModSoundChannelBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &FModSoundChannelBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr FModSoundChannelBase::shallowCopy(void) const 
{ 
    FModSoundChannelPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const FModSoundChannel *>(this)); 

    return returnValue; 
}

UInt32 FModSoundChannelBase::getContainerSize(void) const 
{ 
    return sizeof(FModSoundChannel); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void FModSoundChannelBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((FModSoundChannelBase *) &other, whichField);
}
#else
void FModSoundChannelBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((FModSoundChannelBase *) &other, whichField, sInfo);
}
void FModSoundChannelBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void FModSoundChannelBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

FModSoundChannelBase::FModSoundChannelBase(void) :
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

FModSoundChannelBase::FModSoundChannelBase(const FModSoundChannelBase &source) :
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

FModSoundChannelBase::~FModSoundChannelBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 FModSoundChannelBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void FModSoundChannelBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);


}

void FModSoundChannelBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void FModSoundChannelBase::executeSyncImpl(      FModSoundChannelBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);


}
#else
void FModSoundChannelBase::executeSyncImpl(      FModSoundChannelBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);



}

void FModSoundChannelBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<FModSoundChannelPtr>::_type("FModSoundChannelPtr", "SoundChannelPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(FModSoundChannelPtr, OSG_SOUNDLIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(FModSoundChannelPtr, OSG_SOUNDLIB_DLLTMPLMAPPING);


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: FCBaseTemplate_cpp.h,v 1.47 2006/03/17 17:03:19 pdaehne Exp $";
    static Char8 cvsid_hpp       [] = OSGFMODSOUNDCHANNELBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGFMODSOUNDCHANNELBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGFMODSOUNDCHANNELFIELDS_HEADER_CVSID;
}

OSG_END_NAMESPACE

