/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com), Daniel Guilliams           *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPARTICLEGENERATORDECORATORFIELDS_H_
#define _OSGPARTICLEGENERATORDECORATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribParticleSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class ParticleGeneratorDecorator;

OSG_GEN_CONTAINERPTR(ParticleGeneratorDecorator);

/*! \ingroup GrpContribParticleSystemFieldTraits
    \ingroup GrpLibOSGContribParticleSystem
 */
template <>
struct FieldTraits<ParticleGeneratorDecorator *> :
    public FieldTraitsFCPtrBase<ParticleGeneratorDecorator *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ParticleGeneratorDecorator *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBPARTICLESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFParticleGeneratorDecoratorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFParticleGeneratorDecoratorPtr"; }
};

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecParticleGeneratorDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecParticleGeneratorDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakParticleGeneratorDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdParticleGeneratorDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecParticleGeneratorDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecParticleGeneratorDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakParticleGeneratorDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleGeneratorDecorator *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdParticleGeneratorDecoratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<ParticleGeneratorDecorator *,
                      RecordedRefCountPolicy  > SFRecParticleGeneratorDecoratorPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<ParticleGeneratorDecorator *,
                      UnrecordedRefCountPolicy> SFUnrecParticleGeneratorDecoratorPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<ParticleGeneratorDecorator *,
                      WeakRefCountPolicy      > SFWeakParticleGeneratorDecoratorPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<ParticleGeneratorDecorator *,
                      NoRefCountPolicy        > SFUncountedParticleGeneratorDecoratorPtr;


/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<ParticleGeneratorDecorator *,
                      RecordedRefCountPolicy  > MFRecParticleGeneratorDecoratorPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<ParticleGeneratorDecorator *,
                      UnrecordedRefCountPolicy> MFUnrecParticleGeneratorDecoratorPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<ParticleGeneratorDecorator *,
                      WeakRefCountPolicy      > MFWeakParticleGeneratorDecoratorPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<ParticleGeneratorDecorator *,
                      NoRefCountPolicy        > MFUncountedParticleGeneratorDecoratorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFRecParticleGeneratorDecoratorPtr : 
    public PointerSField<ParticleGeneratorDecorator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUnrecParticleGeneratorDecoratorPtr : 
    public PointerSField<ParticleGeneratorDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFWeakParticleGeneratorDecoratorPtr :
    public PointerSField<ParticleGeneratorDecorator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUncountedParticleGeneratorDecoratorPtr :
    public PointerSField<ParticleGeneratorDecorator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFRecParticleGeneratorDecoratorPtr :
    public PointerMField<ParticleGeneratorDecorator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUnrecParticleGeneratorDecoratorPtr :
    public PointerMField<ParticleGeneratorDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFWeakParticleGeneratorDecoratorPtr :
    public PointerMField<ParticleGeneratorDecorator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUncountedParticleGeneratorDecoratorPtr :
    public PointerMField<ParticleGeneratorDecorator *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPARTICLEGENERATORDECORATORFIELDS_H_ */
