###

LIB_NAME = OSGAnimation
LIB_INCLUDE_DIR_NAME = Animation

srcdir = ../../../src
installdir = ../../../../Builds/Linux
commondir = ../../../../Builds/Common
VPATH = $(srcdir):$(srcdir)/Animations:$(srcdir)/Animators:$(srcdir)/KeyframeSequence:$(srcdir)/Interpolation:$(srcdir)/Animations/Advancers:$(srcdir)/GeometryAnimation:$(srcdir)/KeyframeSequence/GeometryKeyframeSequences:$(srcdir)/Util


#.SUFFIX = .o .o

EXTRA_CCFLAGS = -I$(srcdir)

OBJECTS = OSGAnimator.o \
	OSGKeyframeAnimatorBase.o \
	OSGAnimatorBase.o \
	OSGKeyframeAnimator.o \
	OSGGeoPropertyOperations.o \
	OSGMFieldInterpolations.o \
	OSGInterpolationFactory.o \
	OSGGeometryInterpolations.o \
	OSGKeyframeInterpolations.o \
	OSGKeyframeSequence.o \
	OSGKeyframeSequenceReal32.o \
	OSGKeyframeSequenceImagePtrBase.o \
	OSGKeyframeSequenceNodeCorePtr.o \
	OSGKeyframeSequenceNodeCorePtrBase.o \
	OSGKeyframeSequenceInt32.o \
	OSGKeyframeSequenceStateChunkPtrBase.o \
	OSGKeyframeSequenceTextureChunkPtrBase.o \
	OSGKeyframeSequencePnt3fBase.o \
	OSGKeyframeSequenceColor4f.o \
	OSGKeyframeSequenceVec2f.o \
	OSGKeyframeSequenceStringBase.o \
	OSGKeyframeSequenceMatrix.o \
	OSGKeyframeSequenceColor3f.o \
	OSGKeyframeSequenceGLenum.o \
	OSGKeyframeSequenceVec2fBase.o \
	OSGKeyframeSequenceMaterialPtrBase.o \
	OSGKeyframeSequenceGeoColorsPtr.o \
	OSGKeyframeSequenceGeoColorsPtrBase.o \
	OSGKeyframeSequenceGeoNormalsPtr.o \
	OSGKeyframeSequenceGeoNormalsPtrBase.o \
	OSGKeyframeSequenceGeoPositionsPtrBase.o \
	OSGKeyframeSequenceGeoTexCoordsPtr.o \
	OSGKeyframeSequenceGeoTexCoordsPtrBase.o \
	OSGKeyframeSequenceGeoPositionsPtr.o \
	OSGKeyframeSequenceUInt8Base.o \
	OSGKeyframeSequenceTimeBase.o \
	OSGKeyframeSequenceGLenumBase.o \
	OSGKeyframeSequenceUInt16Base.o \
	OSGKeyframeSequenceUInt8.o \
	OSGKeyframeSequenceTime.o \
	OSGKeyframeSequenceBool.o \
	OSGKeyframeSequenceBase.o \
	OSGKeyframeSequenceQuaternion.o \
	OSGKeyframeSequenceImagePtr.o \
	OSGKeyframeSequenceColor3fBase.o \
	OSGKeyframeSequenceVec3fBase.o \
	OSGKeyframeSequenceUInt16.o \
	OSGKeyframeSequenceQuaternionBase.o \
	OSGKeyframeSequenceStateChunkPtr.o \
	OSGKeyframeSequenceUInt32Base.o \
	OSGKeyframeSequencePnt3f.o \
	OSGKeyframeSequenceVec3f.o \
	OSGKeyframeSequenceUInt32.o \
	OSGKeyframeSequenceColor4fBase.o \
	OSGKeyframeSequenceMatrixBase.o \
	OSGKeyframeSequenceInt32Base.o \
	OSGKeyframeSequenceReal32Base.o \
	OSGKeyframeSequenceOSGNodePtr.o \
	OSGKeyframeSequencePnt2f.o \
	OSGKeyframeSequencePnt2fBase.o \
	OSGKeyframeSequenceBoolBase.o \
	OSGKeyframeSequenceString.o \
	OSGKeyframeSequenceOSGNodePtrBase.o \
	OSGKeyframeSequenceTextureChunkPtr.o \
	OSGKeyframeSequenceMaterialPtr.o \
	OSGFieldAnimation.o \
	OSGFieldAnimationBase.o \
	OSGGeometryAnimation.o \
	OSGFieldAnimationAdvancer.o \
	OSGAnimationAdvancer.o \
	OSGElapsedTimeAnimationAdvancer.o \
	OSGConstantAnimationAdvancerBase.o \
	OSGFieldAnimationAdvancerBase.o \
	OSGElapsedTimeAnimationAdvancerBase.o \
	OSGConstantAnimationAdvancer.o \
	OSGAnimationAdvancerBase.o \
	OSGGeometryAnimationBase.o \
	OSGAnimation.o \
	OSGAnimationBase.o \
	OSGShaderAnimation.o \
	OSGShaderAnimationBase.o \
	OSGBlendGeometry.o \
	OSGGeoNormalDifferenceSet.o \
	OSGGeoPositionDifferenceSetBase.o \
	OSGGeoDifferenceSet.o \
	OSGGeoTexCoordDifferenceSet.o \
	OSGGeoNormalDifferenceSetBase.o \
	OSGGeoTexCoordDifferenceSetBase.o \
	OSGGeoColorDifferenceSet.o \
	OSGGeoPositionDifferenceSet.o \
	OSGGeoColorDifferenceSetBase.o \
	OSGGeoDifferenceSetBase.o \
	OSGBlendGeometryBase.o
        
        
include $(commondir)/CommonMake.mk
