###

LIB_NAME = OSGUserInterface
LIB_INCLUDE_DIR_NAME = UserInterface

srcdir = ../../../src
installdir = ../../../../Builds/Linux
commondir = ../../../../Builds/Common
VPATH = $(srcdir)/:$(srcdir)/Background:$(srcdir)/Border:$(srcdir)/Component:$(srcdir)/Component/List:$(srcdir)/Foreground:$(srcdir)/Graphics:$(srcdir)/Layout:$(srcdir)/LookAndFeel:$(srcdir)/Text:$(srcdir)/Util:


#.SUFFIX = .o .o

EXTRA_CCFLAGS = -I$(srcdir)

OBJECTS = OSGColorUIBackground.o \
	OSGColorUIBackgroundBase.o \
	OSGCompoundUIBackground.o \
	OSGCompoundUIBackgroundBase.o \
	OSGEmptyUIBackground.o \
	OSGEmptyUIBackgroundBase.o \
	OSGGradientUIBackground.o \
	OSGGradientUIBackgroundBase.o \
	OSGMaterialUIBackground.o \
	OSGMaterialUIBackgroundBase.o \
	OSGTextureUIBackground.o \
	OSGTextureUIBackgroundBase.o \
	OSGUIBackground.o \
	OSGUIBackgroundBase.o \
	OSGBevelBorder.o \
	OSGBevelBorderBase.o \
	OSGBorder.o \
	OSGBorderBase.o \
	OSGCompoundBorder.o \
	OSGCompoundBorderBase.o \
	OSGEmptyBorder.o \
	OSGEmptyBorderBase.o \
	OSGEtchedBorder.o \
	OSGEtchedBorderBase.o \
	OSGLineBorder.o \
	OSGLineBorderBase.o \
	OSGMatteBorder.o \
	OSGMatteBorderBase.o \
	OSGButton.o \
	OSGButtonBase.o \
	OSGCanvas.o \
	OSGCanvasBase.o \
	OSGCheckboxButton.o \
	OSGCheckboxButtonBase.o \
	OSGComponent.o \
	OSGComponentBase.o \
	OSGContainer.o \
	OSGContainerBase.o \
	OSGFrame.o \
	OSGFrameBase.o \
	OSGImageComponent.o \
	OSGImageComponentBase.o \
	OSGLabel.o \
	OSGLabelBase.o \
	OSGPanel.o \
	OSGPanelBase.o \
	OSGRadioButton.o \
	OSGRadioButtonBase.o \
	OSGToggleButton.o \
	OSGToggleButtonBase.o \
	OSGAbstractListModel.o \
	OSGAbstractListModelBase.o \
	OSGDefaultListCellGenerator.o \
	OSGDefaultListCellGeneratorBase.o \
	OSGDefaultListSelectionModel.o \
	OSGDefaultListSelectionModelBase.o \
	OSGList.o \
	OSGListBase.o \
	OSGUIForeground.o \
	OSGUIForegroundBase.o \
	OSGGraphics.o \
	OSGGraphics2D.o \
	OSGGraphics2DBase.o \
	OSGGraphicsBase.o \
	OSGAbsoluteLayout.o \
	OSGAbsoluteLayoutBase.o \
	OSGAbsoluteLayoutConstraints.o \
	OSGAbsoluteLayoutConstraintsBase.o \
	OSGBorderLayout.o \
	OSGBorderLayoutBase.o \
	OSGBorderLayoutConstraints.o \
	OSGBorderLayoutConstraintsBase.o \
	OSGBoxLayout.o \
	OSGBoxLayoutBase.o \
	OSGBoxLayoutConstraints.o \
	OSGBoxLayoutConstraintsBase.o \
	OSGCardLayout.o \
	OSGCardLayoutBase.o \
	OSGCardLayoutConstraints.o \
	OSGCardLayoutConstraintsBase.o \
	OSGFlowLayout.o \
	OSGFlowLayoutBase.o \
	OSGFlowLayoutConstraints.o \
	OSGFlowLayoutConstraintsBase.o \
	OSGGridBagLayout.o \
	OSGGridBagLayoutBase.o \
	OSGGridBagLayoutConstraints.o \
	OSGGridBagLayoutConstraintsBase.o \
	OSGGridLayout.o \
	OSGGridLayoutBase.o \
	OSGGridLayoutConstraints.o \
	OSGGridLayoutConstraintsBase.o \
	OSGLayout.o \
	OSGLayoutBase.o \
	OSGLayoutConstraints.o \
	OSGLayoutConstraintsBase.o \
	OSGOverlayLayout.o \
	OSGOverlayLayoutBase.o \
	OSGOverlayLayoutConstraints.o \
	OSGOverlayLayoutConstraintsBase.o \
	OSGDefaultLookAndFeel.o \
	OSGDefaultLookAndFeelBase.o \
	OSGLookAndFeel.o \
	OSGLookAndFeelBase.o \
	OSGLookAndFeelManager.o \
	OSGFont.o \
	OSGFontBase.o \
	OSGUIDrawUtils.o
        
        
include $(commondir)/CommonMake.mk
