###

LIB_NAME = OSGUserInterface
LIB_INCLUDE_DIR_NAME = UserInterface

srcdir = ../../../src
installdir = ../../../../Builds/Linux
commondir = ../../../../Builds/Common
VPATH = $(srcdir)/:$(srcdir)/Border:$(srcdir)/Background:$(srcdir)/Event:$(srcdir)/Layout:$(srcdir)/Util:$(srcdir)/Component:$(srcdir)/Component/Button:$(srcdir)/Component/Menu:$(srcdir)/Component/Scroll:$(srcdir)/Component/Misc:$(srcdir)/Component/Container:$(srcdir)/Component/List:$(srcdir)/Component/Text:$(srcdir)/LookAndFeel:$(srcdir)/UIDrawingSurface:$(srcdir)/UIDrawingSurface/Foreground:$(srcdir)/UIDrawingSurface/NodeCore:$(srcdir)/Graphics:$(srcdir)/Graphics/UIDrawObjects:$(srcdir)/Text:


#.SUFFIX = .o .o

EXTRA_CCFLAGS = -I$(srcdir) -I../../../../Builds/Linux/include

OBJECTS = OSGShadowBorder.o \
	OSGMatteBorderBase.o \
	OSGBorder.o \
	OSGLineBorderBase.o \
	OSGBevelBorder.o \
	OSGEtchedBorderBase.o \
	OSGCompoundBorder.o \
	OSGRoundedCornerLineBorderBase.o \
	OSGLineBorder.o \
	OSGEmptyBorderBase.o \
	OSGMatteBorder.o \
	OSGBorderBase.o \
	OSGShadowBorderBase.o \
	OSGEtchedBorder.o \
	OSGEmptyBorder.o \
	OSGBevelBorderBase.o \
	OSGCompoundBorderBase.o \
	OSGMultiColorMatteBorderBase.o \
	OSGRoundedCornerLineBorder.o \
	OSGMultiColorMatteBorder.o \
	OSGCompoundUIBackground.o \
	OSGMaterialUIBackgroundBase.o \
	OSGGradientUIBackgroundBase.o \
	OSGMaterialUIBackground.o \
	OSGColorUIBackgroundBase.o \
	OSGTextureUIBackground.o \
	OSGUIBackgroundBase.o \
	OSGTextureUIBackgroundBase.o \
	OSGGradientUIBackground.o \
	OSGColorUIBackground.o \
	OSGUIBackground.o \
	OSGEmptyUIBackground.o \
	OSGCompoundUIBackgroundBase.o \
	OSGEmptyUIBackgroundBase.o \
	OSGComponentEvent.o \
	OSGLayout.o \
	OSGGridLayoutConstraints.o \
	OSGBorderLayout.o \
	OSGOverlayLayout.o \
	OSGCardLayoutConstraints.o \
	OSGGridBagLayout.o \
	OSGLayoutConstraints.o \
	OSGLayoutConstraintsBase.o \
	OSGGridBagLayoutBase.o \
	OSGBoxLayout.o \
	OSGLayoutBase.o \
	OSGGridBagLayoutConstraints.o \
	OSGGridLayoutBase.o \
	OSGCardLayoutBase.o \
	OSGBorderLayoutConstraintsBase.o \
	OSGFlowLayoutBase.o \
	OSGOverlayLayoutConstraintsBase.o \
	OSGBoxLayoutBase.o \
	OSGCardLayoutConstraintsBase.o \
	OSGFlowLayoutConstraintsBase.o \
	OSGOverlayLayoutBase.o \
	OSGFlowLayout.o \
	OSGOverlayLayoutConstraints.o \
	OSGAbsoluteLayoutConstraintsBase.o \
	OSGCardLayout.o \
	OSGBorderLayoutBase.o \
	OSGAbsoluteLayoutConstraints.o \
	OSGAbsoluteLayout.o \
	OSGGridBagLayoutConstraintsBase.o \
	OSGBoxLayoutConstraints.o \
	OSGGridLayout.o \
	OSGGridLayoutConstraintsBase.o \
	OSGAbsoluteLayoutBase.o \
	OSGBorderLayoutConstraints.o \
	OSGFlowLayoutConstraints.o \
	OSGBoxLayoutConstraintsBase.o \
	OSGLineUtils.o \
	OSGUIDrawUtils.o \
	OSGLabelBase.o \
	OSGCanvasBase.o \
	OSGRotatedComponent.o \
	OSGUIDrawObjectCanvas.o \
	OSGLabel.o \
	OSGComponent.o \
	OSGRotatedComponentBase.o \
	OSGUIDrawObjectCanvasBase.o \
	OSGCanvas.o \
	OSGImageComponent.o \
	OSGImageComponentBase.o \
	OSGComponentBase.o \
	OSGButtonBase.o \
	OSGRadioButtonGroup.o \
	OSGCheckboxButton.o \
	OSGButton.o \
	OSGToggleButton.o \
	OSGCheckboxButtonBase.o \
	OSGRadioButtonBase.o \
	OSGRadioButton.o \
	OSGToggleButtonBase.o \
	OSGSeperatorMenuItem.o \
	OSGMenuBase.o \
	OSGMenuItemBase.o \
	OSGPopupMenu.o \
	OSGMenuItem.o \
	OSGMenu.o \
	OSGSeperatorMenuItemBase.o \
	OSGPopupMenuBase.o \
	OSGScrollBarBase.o \
	OSGScrollBar.o \
	OSGScrollPanel.o \
	OSGScrollPanelBase.o \
	OSGDefaultBoundedRangeModel.o \
	OSGToolTip.o \
	OSGToolTipBase.o \
	OSGFrameBase.o \
	OSGContainer.o \
	OSGTabPanel.o \
	OSGTabPanelBase.o \
	OSGSplitPanel.o \
	OSGPanelBase.o \
	OSGSplitPanelBase.o \
	OSGPanel.o \
	OSGContainerBase.o \
	OSGFrame.o \
	OSGListBase.o \
	OSGAbstractListModel.o \
	OSGDefaultListSelectionModel.o \
	OSGList.o \
	OSGDefaultListCellGenerator.o \
	OSGTextComponent.o \
	OSGPasswordField.o \
	OSGTextComponentBase.o \
	OSGPasswordFieldBase.o \
	OSGTextArea.o \
	OSGTextAreaBase.o \
	OSGTextField.o \
	OSGTextFieldBase.o \
	OSGLookAndFeelBase.o \
	OSGDefaultLookAndFeelBase.o \
	OSGDefaultLookAndFeel.o \
	OSGLookAndFeelManager.o \
	OSGWindowsLookAndFeelBase.o \
	OSGLookAndFeel.o \
	OSGWindowsLookAndFeel.o \
	OSGUIDrawingSurfaceMouseTransformFunctor.o \
	OSGUIDrawingSurfaceMouseTransformFunctorBase.o \
	OSGUIDrawingSurface.o \
	OSGUIDrawingSurfaceBase.o \
	OSGUIForegroundMouseTransformFunctor.o \
	OSGUIForeground.o \
	OSGUIForegroundMouseTransformFunctorBase.o \
	OSGUIForegroundBase.o \
	OSGUIRectangleMouseTransformFunctorBase.o \
	OSGUIRectangleMouseTransformFunctor.o \
	OSGUIRectangleBase.o \
	OSGUIRectangle.o \
	OSGGraphics2DBase.o \
	OSGGraphics.o \
	OSGGraphics2D.o \
	OSGGraphicsBase.o \
	OSGDiscUIDrawObjectBase.o \
	OSGMultiColoredQuadUIDrawObjectBase.o \
	OSGPolygonUIDrawObjectBase.o \
	OSGRectUIDrawObjectBase.o \
	OSGArcUIDrawObject.o \
	OSGArcUIDrawObjectBase.o \
	OSGMultiColoredQuadUIDrawObject.o \
	OSGDiscUIDrawObject.o \
	OSGLineUIDrawObjectBase.o \
	OSGRectUIDrawObject.o \
	OSGTextUIDrawObjectBase.o \
	OSGTextUIDrawObject.o \
	OSGLineUIDrawObject.o \
	OSGUIDrawObjectBase.o \
	OSGPolygonUIDrawObject.o \
	OSGUIDrawObject.o \
	OSGUIFont.o \
	OSGUIFontBase.o
        
        
include $(commondir)/CommonMake.mk
