###

LIB_NAME = OSGDynamics
LIB_INCLUDE_DIR_NAME = Dynamics

srcdir = ../../../src
installdir = ../../../../Builds/Linux
commondir = ../../../../Builds/Common
VPATH = $(srcdir)/:$(srcdir)/Distributions:$(srcdir)/Distributions/1D:$(srcdir)/Distributions/2D:$(srcdir)/Distributions/3D:$(srcdir)/Function:


#.SUFFIX = .o .o

EXTRA_CCFLAGS = -I$(srcdir)

OBJECTS = OSGSegmentDistribution1D.o \
	OSGSegmentSetDistribution1D.o \
	OSGDistribution1D.o \
	OSGGaussianNormalDistribution1D.o \
	OSGSegmentDistribution1DBase.o \
	OSGSegmentSetDistribution1DBase.o \
	OSGDistribution1DBase.o \
	OSGGaussianNormalDistribution1DBase.o \
	OSGGaussianNormaDistribution2DBase.o \
	OSGTriangleDistribution2D.o \
	OSGDistribution2DBase.o \
	OSGLineDistribution2DBase.o \
	OSGDiscDistribution2D.o \
	OSGQuadDistribution2DBase.o \
	OSGTriangleDistribution2DBase.o \
	OSGGaussianNormaDistribution2D.o \
	OSGDiscDistribution2DBase.o \
	OSGDistribution2D.o \
	OSGLineDistribution2D.o \
	OSGQuadDistribution2D.o \
	OSGCylinderDistribution3D.o \
	OSGDistribution3D.o \
	OSGGaussianNormalDistribution3D.o \
	OSGBoxDistribution3DBase.o \
	OSGLineDistribution3D.o \
	OSGGeoVolumeDistribution3DBase.o \
	OSGTriDistribution3D.o \
	OSGSphereDistribution3DBase.o \
	OSGBoxDistribution3D.o \
	OSGGeoVolumeDistribution3D.o \
	OSGDiscDistribution3DBase.o \
	OSGGeoSurfaceDistribution3DBase.o \
	OSGSphereDistribution3D.o \
	OSGCylinderDistribution3DBase.o \
	OSGDistribution3DBase.o \
	OSGGaussianNormalDistribution3DBase.o \
	OSGLineDistribution3DBase.o \
	OSGDiscDistribution3D.o \
	OSGGeoSurfaceDistribution3D.o \
	OSGTriDistribution3DBase.o \
	OSGOutputVec3fFunctionBase.o \
	OSGOutputVec2fFunction.o \
	OSGOutputPnt2fFunctionBase.o \
	OSGOutputReal32Function.o \
	OSGOutputPnt3fFunction.o \
	OSGFunction.o \
	OSGOutputVec2fFunctionBase.o \
	OSGOutputVec3fFunction.o \
	OSGOutputReal32FunctionBase.o \
	OSGOutputPnt3fFunctionBase.o \
	OSGFunctionBase.o \
	OSGOutputPnt2fFunction.o
        
        
include $(commondir)/CommonMake.mk
