/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox Particle System                        *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *                          Authors: David Kabala                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class RandomMovementParticleAffector!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILERANDOMMOVEMENTPARTICLEAFFECTORINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGRandomMovementParticleAffectorBase.h"
#include "OSGRandomMovementParticleAffector.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  RandomMovementParticleAffectorBase::AttributeAffectedFieldMask = 
    (TypeTraits<BitVector>::One << RandomMovementParticleAffectorBase::AttributeAffectedFieldId);

const OSG::BitVector  RandomMovementParticleAffectorBase::MagnitudeFieldMask = 
    (TypeTraits<BitVector>::One << RandomMovementParticleAffectorBase::MagnitudeFieldId);

const OSG::BitVector  RandomMovementParticleAffectorBase::SmoothFieldMask = 
    (TypeTraits<BitVector>::One << RandomMovementParticleAffectorBase::SmoothFieldId);

const OSG::BitVector RandomMovementParticleAffectorBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var UInt32          RandomMovementParticleAffectorBase::_sfAttributeAffected
    
*/
/*! \var Real32          RandomMovementParticleAffectorBase::_sfMagnitude
    
*/
/*! \var bool            RandomMovementParticleAffectorBase::_sfSmooth
    
*/

//! RandomMovementParticleAffector description

FieldDescription *RandomMovementParticleAffectorBase::_desc[] = 
{
    new FieldDescription(SFUInt32::getClassType(), 
                     "AttributeAffected", 
                     AttributeAffectedFieldId, AttributeAffectedFieldMask,
                     false,
                     (FieldAccessMethod) &RandomMovementParticleAffectorBase::getSFAttributeAffected),
    new FieldDescription(SFReal32::getClassType(), 
                     "Magnitude", 
                     MagnitudeFieldId, MagnitudeFieldMask,
                     false,
                     (FieldAccessMethod) &RandomMovementParticleAffectorBase::getSFMagnitude),
    new FieldDescription(SFBool::getClassType(), 
                     "Smooth", 
                     SmoothFieldId, SmoothFieldMask,
                     false,
                     (FieldAccessMethod) &RandomMovementParticleAffectorBase::getSFSmooth)
};


FieldContainerType RandomMovementParticleAffectorBase::_type(
    "RandomMovementParticleAffector",
    "ParticleAffector",
    NULL,
    (PrototypeCreateF) &RandomMovementParticleAffectorBase::createEmpty,
    RandomMovementParticleAffector::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(RandomMovementParticleAffectorBase, RandomMovementParticleAffectorPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &RandomMovementParticleAffectorBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &RandomMovementParticleAffectorBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr RandomMovementParticleAffectorBase::shallowCopy(void) const 
{ 
    RandomMovementParticleAffectorPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const RandomMovementParticleAffector *>(this)); 

    return returnValue; 
}

UInt32 RandomMovementParticleAffectorBase::getContainerSize(void) const 
{ 
    return sizeof(RandomMovementParticleAffector); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void RandomMovementParticleAffectorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((RandomMovementParticleAffectorBase *) &other, whichField);
}
#else
void RandomMovementParticleAffectorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((RandomMovementParticleAffectorBase *) &other, whichField, sInfo);
}
void RandomMovementParticleAffectorBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void RandomMovementParticleAffectorBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

RandomMovementParticleAffectorBase::RandomMovementParticleAffectorBase(void) :
    _sfAttributeAffected      (UInt32(RandomMovementParticleAffector::POSITION_ATTRIBUTE)), 
    _sfMagnitude              (Real32(1.0f)), 
    _sfSmooth                 (bool(true)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

RandomMovementParticleAffectorBase::RandomMovementParticleAffectorBase(const RandomMovementParticleAffectorBase &source) :
    _sfAttributeAffected      (source._sfAttributeAffected      ), 
    _sfMagnitude              (source._sfMagnitude              ), 
    _sfSmooth                 (source._sfSmooth                 ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

RandomMovementParticleAffectorBase::~RandomMovementParticleAffectorBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 RandomMovementParticleAffectorBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (AttributeAffectedFieldMask & whichField))
    {
        returnValue += _sfAttributeAffected.getBinSize();
    }

    if(FieldBits::NoField != (MagnitudeFieldMask & whichField))
    {
        returnValue += _sfMagnitude.getBinSize();
    }

    if(FieldBits::NoField != (SmoothFieldMask & whichField))
    {
        returnValue += _sfSmooth.getBinSize();
    }


    return returnValue;
}

void RandomMovementParticleAffectorBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (AttributeAffectedFieldMask & whichField))
    {
        _sfAttributeAffected.copyToBin(pMem);
    }

    if(FieldBits::NoField != (MagnitudeFieldMask & whichField))
    {
        _sfMagnitude.copyToBin(pMem);
    }

    if(FieldBits::NoField != (SmoothFieldMask & whichField))
    {
        _sfSmooth.copyToBin(pMem);
    }


}

void RandomMovementParticleAffectorBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (AttributeAffectedFieldMask & whichField))
    {
        _sfAttributeAffected.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (MagnitudeFieldMask & whichField))
    {
        _sfMagnitude.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (SmoothFieldMask & whichField))
    {
        _sfSmooth.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void RandomMovementParticleAffectorBase::executeSyncImpl(      RandomMovementParticleAffectorBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (AttributeAffectedFieldMask & whichField))
        _sfAttributeAffected.syncWith(pOther->_sfAttributeAffected);

    if(FieldBits::NoField != (MagnitudeFieldMask & whichField))
        _sfMagnitude.syncWith(pOther->_sfMagnitude);

    if(FieldBits::NoField != (SmoothFieldMask & whichField))
        _sfSmooth.syncWith(pOther->_sfSmooth);


}
#else
void RandomMovementParticleAffectorBase::executeSyncImpl(      RandomMovementParticleAffectorBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (AttributeAffectedFieldMask & whichField))
        _sfAttributeAffected.syncWith(pOther->_sfAttributeAffected);

    if(FieldBits::NoField != (MagnitudeFieldMask & whichField))
        _sfMagnitude.syncWith(pOther->_sfMagnitude);

    if(FieldBits::NoField != (SmoothFieldMask & whichField))
        _sfSmooth.syncWith(pOther->_sfSmooth);



}

void RandomMovementParticleAffectorBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<RandomMovementParticleAffectorPtr>::_type("RandomMovementParticleAffectorPtr", "ParticleAffectorPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(RandomMovementParticleAffectorPtr, OSG_PARTICLESYSTEMLIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(RandomMovementParticleAffectorPtr, OSG_PARTICLESYSTEMLIB_DLLTMPLMAPPING);


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: FCBaseTemplate_cpp.h,v 1.47 2006/03/17 17:03:19 pdaehne Exp $";
    static Char8 cvsid_hpp       [] = OSGRANDOMMOVEMENTPARTICLEAFFECTORBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGRANDOMMOVEMENTPARTICLEAFFECTORBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGRANDOMMOVEMENTPARTICLEAFFECTORFIELDS_HEADER_CVSID;
}

OSG_END_NAMESPACE

