/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class AbstractDocument!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGElement.h"                 // RootElement Class

#include "OSGAbstractDocumentBase.h"
#include "OSGAbstractDocument.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::AbstractDocument
    UI AbstractDocument.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Element *       AbstractDocumentBase::_sfRootElement
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<AbstractDocument *>::_type("AbstractDocumentPtr", "DocumentPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(AbstractDocument *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           AbstractDocument *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           AbstractDocument *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void AbstractDocumentBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecElementPtr::Description(
        SFUnrecElementPtr::getClassType(),
        "RootElement",
        "",
        RootElementFieldId, RootElementFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&AbstractDocument::editHandleRootElement),
        static_cast<FieldGetMethodSig >(&AbstractDocument::getHandleRootElement));

    oType.addInitialDesc(pDesc);
}


AbstractDocumentBase::TypeObject AbstractDocumentBase::_type(
    AbstractDocumentBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    NULL,
    AbstractDocument::initMethod,
    AbstractDocument::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&AbstractDocument::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"AbstractDocument\"\n"
    "\tparent=\"Document\"\n"
    "    library=\"ContribTextDom\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"false\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "UI AbstractDocument.\n"
    "\t<Field\n"
    "\t\tname=\"RootElement\"\n"
    "\t\ttype=\"Element\"\n"
    "\t\tcategory=\"pointer\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\tdefaultValue=\"NULL\"\n"
    "\t\taccess=\"protected\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    "UI AbstractDocument.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &AbstractDocumentBase::getType(void)
{
    return _type;
}

const FieldContainerType &AbstractDocumentBase::getType(void) const
{
    return _type;
}

UInt32 AbstractDocumentBase::getContainerSize(void) const
{
    return sizeof(AbstractDocument);
}

/*------------------------- decorator get ------------------------------*/


//! Get the AbstractDocument::_sfRootElement field.
const SFUnrecElementPtr *AbstractDocumentBase::getSFRootElement(void) const
{
    return &_sfRootElement;
}

SFUnrecElementPtr   *AbstractDocumentBase::editSFRootElement    (void)
{
    editSField(RootElementFieldMask);

    return &_sfRootElement;
}





/*------------------------------ access -----------------------------------*/

UInt32 AbstractDocumentBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (RootElementFieldMask & whichField))
    {
        returnValue += _sfRootElement.getBinSize();
    }

    return returnValue;
}

void AbstractDocumentBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (RootElementFieldMask & whichField))
    {
        _sfRootElement.copyToBin(pMem);
    }
}

void AbstractDocumentBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (RootElementFieldMask & whichField))
    {
        _sfRootElement.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

AbstractDocumentBase::AbstractDocumentBase(void) :
    Inherited(),
    _sfRootElement            (NULL)
{
}

AbstractDocumentBase::AbstractDocumentBase(const AbstractDocumentBase &source) :
    Inherited(source),
    _sfRootElement            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

AbstractDocumentBase::~AbstractDocumentBase(void)
{
}

void AbstractDocumentBase::onCreate(const AbstractDocument *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        AbstractDocument *pThis = static_cast<AbstractDocument *>(this);

        pThis->setRootElement(source->getRootElement());
    }
}

GetFieldHandlePtr AbstractDocumentBase::getHandleRootElement     (void) const
{
    SFUnrecElementPtr::GetHandlePtr returnValue(
        new  SFUnrecElementPtr::GetHandle(
             &_sfRootElement,
             this->getType().getFieldDesc(RootElementFieldId),
             const_cast<AbstractDocumentBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr AbstractDocumentBase::editHandleRootElement    (void)
{
    SFUnrecElementPtr::EditHandlePtr returnValue(
        new  SFUnrecElementPtr::EditHandle(
             &_sfRootElement,
             this->getType().getFieldDesc(RootElementFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&AbstractDocument::setRootElement,
                    static_cast<AbstractDocument *>(this), _1));

    editSField(RootElementFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void AbstractDocumentBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    AbstractDocument *pThis = static_cast<AbstractDocument *>(this);

    pThis->execSync(static_cast<AbstractDocument *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void AbstractDocumentBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<AbstractDocument *>(this)->setRootElement(NULL);


}


OSG_END_NAMESPACE
