/*---------------------------------------------------------------------------*\
 *                        OpenSG ToolBox Game                                *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *                          Authors: David Kabala                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Mission!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILEMISSIONINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGMissionBase.h"
#include "OSGMission.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  MissionBase::MissionsFieldMask = 
    (TypeTraits<BitVector>::One << MissionBase::MissionsFieldId);

const OSG::BitVector  MissionBase::PropertiesFieldMask = 
    (TypeTraits<BitVector>::One << MissionBase::PropertiesFieldId);

const OSG::BitVector  MissionBase::DescriptionFieldMask = 
    (TypeTraits<BitVector>::One << MissionBase::DescriptionFieldId);

const OSG::BitVector MissionBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var MissionPtr      MissionBase::_mfMissions
    
*/
/*! \var StringToUInt32Map MissionBase::_mfProperties
    
*/
/*! \var std::string     MissionBase::_sfDescription
    
*/

//! Mission description

FieldDescription *MissionBase::_desc[] = 
{
    new FieldDescription(MFMissionPtr::getClassType(), 
                     "Missions", 
                     MissionsFieldId, MissionsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&MissionBase::editMFMissions)),
    new FieldDescription(MFStringToUInt32Map::getClassType(), 
                     "Properties", 
                     PropertiesFieldId, PropertiesFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&MissionBase::editMFProperties)),
    new FieldDescription(SFString::getClassType(), 
                     "Description", 
                     DescriptionFieldId, DescriptionFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&MissionBase::editSFDescription))
};


FieldContainerType MissionBase::_type(
    "Mission",
    "AttachmentContainer",
    NULL,
    NULL, 
    Mission::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(MissionBase, MissionPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &MissionBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &MissionBase::getType(void) const 
{
    return _type;
} 


UInt32 MissionBase::getContainerSize(void) const 
{ 
    return sizeof(Mission); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void MissionBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<MissionBase *>(&other),
                          whichField);
}
#else
void MissionBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((MissionBase *) &other, whichField, sInfo);
}
void MissionBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void MissionBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

    _mfMissions.terminateShare(uiAspect, this->getContainerSize());
    _mfProperties.terminateShare(uiAspect, this->getContainerSize());
}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

MissionBase::MissionBase(void) :
    _mfMissions               (), 
    _mfProperties             (), 
    _sfDescription            (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

MissionBase::MissionBase(const MissionBase &source) :
    _mfMissions               (source._mfMissions               ), 
    _mfProperties             (source._mfProperties             ), 
    _sfDescription            (source._sfDescription            ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

MissionBase::~MissionBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 MissionBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (MissionsFieldMask & whichField))
    {
        returnValue += _mfMissions.getBinSize();
    }

    if(FieldBits::NoField != (PropertiesFieldMask & whichField))
    {
        returnValue += _mfProperties.getBinSize();
    }

    if(FieldBits::NoField != (DescriptionFieldMask & whichField))
    {
        returnValue += _sfDescription.getBinSize();
    }


    return returnValue;
}

void MissionBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (MissionsFieldMask & whichField))
    {
        _mfMissions.copyToBin(pMem);
    }

    if(FieldBits::NoField != (PropertiesFieldMask & whichField))
    {
        _mfProperties.copyToBin(pMem);
    }

    if(FieldBits::NoField != (DescriptionFieldMask & whichField))
    {
        _sfDescription.copyToBin(pMem);
    }


}

void MissionBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (MissionsFieldMask & whichField))
    {
        _mfMissions.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (PropertiesFieldMask & whichField))
    {
        _mfProperties.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (DescriptionFieldMask & whichField))
    {
        _sfDescription.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void MissionBase::executeSyncImpl(      MissionBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (MissionsFieldMask & whichField))
        _mfMissions.syncWith(pOther->_mfMissions);

    if(FieldBits::NoField != (PropertiesFieldMask & whichField))
        _mfProperties.syncWith(pOther->_mfProperties);

    if(FieldBits::NoField != (DescriptionFieldMask & whichField))
        _sfDescription.syncWith(pOther->_sfDescription);


}
#else
void MissionBase::executeSyncImpl(      MissionBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (DescriptionFieldMask & whichField))
        _sfDescription.syncWith(pOther->_sfDescription);


    if(FieldBits::NoField != (MissionsFieldMask & whichField))
        _mfMissions.syncWith(pOther->_mfMissions, sInfo);

    if(FieldBits::NoField != (PropertiesFieldMask & whichField))
        _mfProperties.syncWith(pOther->_mfProperties, sInfo);


}

void MissionBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

    if(FieldBits::NoField != (MissionsFieldMask & whichField))
        _mfMissions.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (PropertiesFieldMask & whichField))
        _mfProperties.beginEdit(uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<MissionPtr>::_type("MissionPtr", "AttachmentContainerPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(MissionPtr, OSG_GAMELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(MissionPtr, OSG_GAMELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

