/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class LuaErrorEventDetails!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGLuaErrorEventDetailsBase.h"
#include "OSGLuaErrorEventDetails.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::LuaErrorEventDetails
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var VoidP           LuaErrorEventDetailsBase::_sfLuaStateVoidP
    
*/

/*! \var Int32           LuaErrorEventDetailsBase::_sfStatus
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<LuaErrorEventDetails *>::_type("LuaErrorEventDetailsPtr", "EventDetailsPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(LuaErrorEventDetails *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           LuaErrorEventDetails *,
                           0);


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void LuaErrorEventDetailsBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFVoidP::Description(
        SFVoidP::getClassType(),
        "LuaStateVoidP",
        "",
        LuaStateVoidPFieldId, LuaStateVoidPFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&LuaErrorEventDetails::editHandleLuaStateVoidP),
        static_cast<FieldGetMethodSig >(&LuaErrorEventDetails::getHandleLuaStateVoidP));

    oType.addInitialDesc(pDesc);

    pDesc = new SFInt32::Description(
        SFInt32::getClassType(),
        "Status",
        "",
        StatusFieldId, StatusFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&LuaErrorEventDetails::editHandleStatus),
        static_cast<FieldGetMethodSig >(&LuaErrorEventDetails::getHandleStatus));

    oType.addInitialDesc(pDesc);
}


LuaErrorEventDetailsBase::TypeObject LuaErrorEventDetailsBase::_type(
    LuaErrorEventDetailsBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&LuaErrorEventDetailsBase::createEmptyLocal),
    LuaErrorEventDetails::initMethod,
    LuaErrorEventDetails::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&LuaErrorEventDetails::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"LuaErrorEventDetails\"\n"
    "\tparent=\"EventDetails\"\n"
    "    library=\"ContribLua\"\n"
    "    pointerfieldtypes=\"single\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    isBundle=\"true\"\n"
    "\tsupportUnregisteredCreate=\"true\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "    <Field\n"
    "        name=\"LuaStateVoidP\"\n"
    "        type=\"VoidP\"\n"
    "\t\tcategory=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"protected\"\n"
    "        defaultValue=\"NULL\"\n"
    "        publicRead=\"true\"\n"
    "    >\n"
    "    </Field>\n"
    "\t<Field\n"
    "\t\tname=\"Status\"\n"
    "\t\ttype=\"Int32\"\n"
    "\t\tcategory=\"data\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"internal\"\n"
    "\t\taccess=\"protected\"\n"
    "\t\tdefaultValue=\"0\"\n"
    "        publicRead=\"true\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &LuaErrorEventDetailsBase::getType(void)
{
    return _type;
}

const FieldContainerType &LuaErrorEventDetailsBase::getType(void) const
{
    return _type;
}

UInt32 LuaErrorEventDetailsBase::getContainerSize(void) const
{
    return sizeof(LuaErrorEventDetails);
}

/*------------------------- decorator get ------------------------------*/


SFVoidP *LuaErrorEventDetailsBase::editSFLuaStateVoidP(void)
{
    editSField(LuaStateVoidPFieldMask);

    return &_sfLuaStateVoidP;
}

const SFVoidP *LuaErrorEventDetailsBase::getSFLuaStateVoidP(void) const
{
    return &_sfLuaStateVoidP;
}


SFInt32 *LuaErrorEventDetailsBase::editSFStatus(void)
{
    editSField(StatusFieldMask);

    return &_sfStatus;
}

const SFInt32 *LuaErrorEventDetailsBase::getSFStatus(void) const
{
    return &_sfStatus;
}






/*------------------------------ access -----------------------------------*/

UInt32 LuaErrorEventDetailsBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (LuaStateVoidPFieldMask & whichField))
    {
        returnValue += _sfLuaStateVoidP.getBinSize();
    }
    if(FieldBits::NoField != (StatusFieldMask & whichField))
    {
        returnValue += _sfStatus.getBinSize();
    }

    return returnValue;
}

void LuaErrorEventDetailsBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (LuaStateVoidPFieldMask & whichField))
    {
        _sfLuaStateVoidP.copyToBin(pMem);
    }
    if(FieldBits::NoField != (StatusFieldMask & whichField))
    {
        _sfStatus.copyToBin(pMem);
    }
}

void LuaErrorEventDetailsBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (LuaStateVoidPFieldMask & whichField))
    {
        _sfLuaStateVoidP.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (StatusFieldMask & whichField))
    {
        _sfStatus.copyFromBin(pMem);
    }
}

//! create a new instance of the class
LuaErrorEventDetailsTransitPtr LuaErrorEventDetailsBase::createLocal(BitVector bFlags)
{
    LuaErrorEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<LuaErrorEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
LuaErrorEventDetailsTransitPtr LuaErrorEventDetailsBase::createDependent(BitVector bFlags)
{
    LuaErrorEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<LuaErrorEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
LuaErrorEventDetailsTransitPtr LuaErrorEventDetailsBase::create(void)
{
    return createLocal();
}

LuaErrorEventDetails *LuaErrorEventDetailsBase::createEmptyLocal(BitVector bFlags)
{
    LuaErrorEventDetails *returnValue;

    newPtr<LuaErrorEventDetails>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
LuaErrorEventDetails *LuaErrorEventDetailsBase::createEmpty(void)
{
    return createEmptyLocal();
}

LuaErrorEventDetails *LuaErrorEventDetailsBase::createUnregistered(void)
{
    LuaErrorEventDetails *returnValue = new LuaErrorEventDetails;

#ifdef OSG_MT_CPTR_ASPECT
    returnValue->setupAspectStore();
#endif
    //Do not register with the FieldContainer Factory

    returnValue->onCreate      (      );
    returnValue->onCreateAspect(returnValue);
    
    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();
    
    return returnValue;
}

FieldContainerTransitPtr LuaErrorEventDetailsBase::shallowCopyLocal(
    BitVector bFlags) const
{
    LuaErrorEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const LuaErrorEventDetails *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr LuaErrorEventDetailsBase::shallowCopyDependent(
    BitVector bFlags) const
{
    LuaErrorEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const LuaErrorEventDetails *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr LuaErrorEventDetailsBase::shallowCopy(void) const
{
    return shallowCopyLocal();
}



/*------------------------- constructors ----------------------------------*/

LuaErrorEventDetailsBase::LuaErrorEventDetailsBase(void) :
    Inherited(),
    _sfLuaStateVoidP          (VoidP(NULL)),
    _sfStatus                 (Int32(0))
{
}

LuaErrorEventDetailsBase::LuaErrorEventDetailsBase(const LuaErrorEventDetailsBase &source) :
    Inherited(source),
    _sfLuaStateVoidP          (source._sfLuaStateVoidP          ),
    _sfStatus                 (source._sfStatus                 )
{
}


/*-------------------------- destructors ----------------------------------*/

LuaErrorEventDetailsBase::~LuaErrorEventDetailsBase(void)
{
}


GetFieldHandlePtr LuaErrorEventDetailsBase::getHandleLuaStateVoidP   (void) const
{
    SFVoidP::GetHandlePtr returnValue(
        new  SFVoidP::GetHandle(
             &_sfLuaStateVoidP,
             this->getType().getFieldDesc(LuaStateVoidPFieldId),
             const_cast<LuaErrorEventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr LuaErrorEventDetailsBase::editHandleLuaStateVoidP  (void)
{
    SFVoidP::EditHandlePtr returnValue(
        new  SFVoidP::EditHandle(
             &_sfLuaStateVoidP,
             this->getType().getFieldDesc(LuaStateVoidPFieldId),
             this));


    editSField(LuaStateVoidPFieldMask);

    return returnValue;
}

GetFieldHandlePtr LuaErrorEventDetailsBase::getHandleStatus          (void) const
{
    SFInt32::GetHandlePtr returnValue(
        new  SFInt32::GetHandle(
             &_sfStatus,
             this->getType().getFieldDesc(StatusFieldId),
             const_cast<LuaErrorEventDetailsBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr LuaErrorEventDetailsBase::editHandleStatus         (void)
{
    SFInt32::EditHandlePtr returnValue(
        new  SFInt32::EditHandle(
             &_sfStatus,
             this->getType().getFieldDesc(StatusFieldId),
             this));


    editSField(StatusFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void LuaErrorEventDetailsBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    LuaErrorEventDetails *pThis = static_cast<LuaErrorEventDetails *>(this);

    pThis->execSync(static_cast<LuaErrorEventDetails *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *LuaErrorEventDetailsBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    LuaErrorEventDetails *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const LuaErrorEventDetails *>(pRefAspect),
                  dynamic_cast<const LuaErrorEventDetails *>(this));

    return returnValue;
}
#endif

void LuaErrorEventDetailsBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
