/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BoxLayoutConstraints!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGBoxLayoutConstraintsBase.h"
#include "OSGBoxLayoutConstraints.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BoxLayoutConstraints
    A UI BoxLayoutConstraints.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<BoxLayoutConstraints *>::_type("BoxLayoutConstraintsPtr", "LayoutConstraintsPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(BoxLayoutConstraints *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BoxLayoutConstraints *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BoxLayoutConstraints *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BoxLayoutConstraintsBase::classDescInserter(TypeObject &oType)
{
}


BoxLayoutConstraintsBase::TypeObject BoxLayoutConstraintsBase::_type(
    BoxLayoutConstraintsBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&BoxLayoutConstraintsBase::createEmptyLocal),
    BoxLayoutConstraints::initMethod,
    BoxLayoutConstraints::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BoxLayoutConstraints::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"BoxLayoutConstraints\"\n"
    "\tparent=\"LayoutConstraints\"\n"
    "    library=\"ContribUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI BoxLayoutConstraints.\n"
    "</FieldContainer>\n",
    "A UI BoxLayoutConstraints.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BoxLayoutConstraintsBase::getType(void)
{
    return _type;
}

const FieldContainerType &BoxLayoutConstraintsBase::getType(void) const
{
    return _type;
}

UInt32 BoxLayoutConstraintsBase::getContainerSize(void) const
{
    return sizeof(BoxLayoutConstraints);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 BoxLayoutConstraintsBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void BoxLayoutConstraintsBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void BoxLayoutConstraintsBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
BoxLayoutConstraintsTransitPtr BoxLayoutConstraintsBase::createLocal(BitVector bFlags)
{
    BoxLayoutConstraintsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BoxLayoutConstraints>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BoxLayoutConstraintsTransitPtr BoxLayoutConstraintsBase::createDependent(BitVector bFlags)
{
    BoxLayoutConstraintsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BoxLayoutConstraints>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BoxLayoutConstraintsTransitPtr BoxLayoutConstraintsBase::create(void)
{
    BoxLayoutConstraintsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BoxLayoutConstraints>(tmpPtr);
    }

    return fc;
}

BoxLayoutConstraints *BoxLayoutConstraintsBase::createEmptyLocal(BitVector bFlags)
{
    BoxLayoutConstraints *returnValue;

    newPtr<BoxLayoutConstraints>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BoxLayoutConstraints *BoxLayoutConstraintsBase::createEmpty(void)
{
    BoxLayoutConstraints *returnValue;

    newPtr<BoxLayoutConstraints>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr BoxLayoutConstraintsBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BoxLayoutConstraints *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BoxLayoutConstraints *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BoxLayoutConstraintsBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BoxLayoutConstraints *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BoxLayoutConstraints *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BoxLayoutConstraintsBase::shallowCopy(void) const
{
    BoxLayoutConstraints *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BoxLayoutConstraints *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

BoxLayoutConstraintsBase::BoxLayoutConstraintsBase(void) :
    Inherited()
{
}

BoxLayoutConstraintsBase::BoxLayoutConstraintsBase(const BoxLayoutConstraintsBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

BoxLayoutConstraintsBase::~BoxLayoutConstraintsBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void BoxLayoutConstraintsBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BoxLayoutConstraints *pThis = static_cast<BoxLayoutConstraints *>(this);

    pThis->execSync(static_cast<BoxLayoutConstraints *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BoxLayoutConstraintsBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BoxLayoutConstraints *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BoxLayoutConstraints *>(pRefAspect),
                  dynamic_cast<const BoxLayoutConstraints *>(this));

    return returnValue;
}
#endif

void BoxLayoutConstraintsBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
