/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGGRIDLAYOUTFIELDS_H_
#define _OSGGRIDLAYOUTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class GridLayout;

OSG_GEN_CONTAINERPTR(GridLayout);

/*! \ingroup GrpContribUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribUserInterface
 */
template <>
struct FieldTraits<GridLayout *> :
    public FieldTraitsFCPtrBase<GridLayout *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<GridLayout *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFGridLayoutPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFGridLayoutPtr"; }
};

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecGridLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecGridLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakGridLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdGridLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecGridLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecGridLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakGridLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<GridLayout *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdGridLayoutPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<GridLayout *,
                      RecordedRefCountPolicy  > SFRecGridLayoutPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<GridLayout *,
                      UnrecordedRefCountPolicy> SFUnrecGridLayoutPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<GridLayout *,
                      WeakRefCountPolicy      > SFWeakGridLayoutPtr;
/*! \ingroup GrpContribUserInterfaceFieldSFields */
typedef PointerSField<GridLayout *,
                      NoRefCountPolicy        > SFUncountedGridLayoutPtr;


/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<GridLayout *,
                      RecordedRefCountPolicy  > MFRecGridLayoutPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<GridLayout *,
                      UnrecordedRefCountPolicy> MFUnrecGridLayoutPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<GridLayout *,
                      WeakRefCountPolicy      > MFWeakGridLayoutPtr;
/*! \ingroup GrpContribUserInterfaceFieldMFields */
typedef PointerMField<GridLayout *,
                      NoRefCountPolicy        > MFUncountedGridLayoutPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFRecGridLayoutPtr : 
    public PointerSField<GridLayout *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUnrecGridLayoutPtr : 
    public PointerSField<GridLayout *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFWeakGridLayoutPtr :
    public PointerSField<GridLayout *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldSFields \ingroup GrpLibOSGContribUserInterface */
struct SFUncountedGridLayoutPtr :
    public PointerSField<GridLayout *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFRecGridLayoutPtr :
    public PointerMField<GridLayout *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUnrecGridLayoutPtr :
    public PointerMField<GridLayout *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFWeakGridLayoutPtr :
    public PointerMField<GridLayout *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribUserInterfaceFieldMFields \ingroup GrpLibOSGContribUserInterface */
struct MFUncountedGridLayoutPtr :
    public PointerMField<GridLayout *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGGRIDLAYOUTFIELDS_H_ */
