/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ForegroundFieldContainerEditor!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGForegroundFieldContainerEditorBase.h"
#include "OSGForegroundFieldContainerEditor.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ForegroundFieldContainerEditor
    FieldContainerEditor for OSG::Foreground
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<ForegroundFieldContainerEditor *>::_type("ForegroundFieldContainerEditorPtr", "ScenePreviewFieldContainerEditorPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(ForegroundFieldContainerEditor *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ForegroundFieldContainerEditor *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ForegroundFieldContainerEditor *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ForegroundFieldContainerEditorBase::classDescInserter(TypeObject &oType)
{
}


ForegroundFieldContainerEditorBase::TypeObject ForegroundFieldContainerEditorBase::_type(
    ForegroundFieldContainerEditorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&ForegroundFieldContainerEditorBase::createEmptyLocal),
    ForegroundFieldContainerEditor::initMethod,
    ForegroundFieldContainerEditor::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ForegroundFieldContainerEditor::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"ForegroundFieldContainerEditor\"\n"
    "\tparent=\"ScenePreviewFieldContainerEditor\"\n"
    "    library=\"ContribFieldContainerEditor\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    ">\n"
    "FieldContainerEditor for OSG::Foreground\n"
    "</FieldContainer>\n",
    "FieldContainerEditor for OSG::Foreground\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ForegroundFieldContainerEditorBase::getType(void)
{
    return _type;
}

const FieldContainerType &ForegroundFieldContainerEditorBase::getType(void) const
{
    return _type;
}

UInt32 ForegroundFieldContainerEditorBase::getContainerSize(void) const
{
    return sizeof(ForegroundFieldContainerEditor);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 ForegroundFieldContainerEditorBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ForegroundFieldContainerEditorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ForegroundFieldContainerEditorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
ForegroundFieldContainerEditorTransitPtr ForegroundFieldContainerEditorBase::createLocal(BitVector bFlags)
{
    ForegroundFieldContainerEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ForegroundFieldContainerEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ForegroundFieldContainerEditorTransitPtr ForegroundFieldContainerEditorBase::createDependent(BitVector bFlags)
{
    ForegroundFieldContainerEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ForegroundFieldContainerEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ForegroundFieldContainerEditorTransitPtr ForegroundFieldContainerEditorBase::create(void)
{
    ForegroundFieldContainerEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ForegroundFieldContainerEditor>(tmpPtr);
    }

    return fc;
}

ForegroundFieldContainerEditor *ForegroundFieldContainerEditorBase::createEmptyLocal(BitVector bFlags)
{
    ForegroundFieldContainerEditor *returnValue;

    newPtr<ForegroundFieldContainerEditor>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ForegroundFieldContainerEditor *ForegroundFieldContainerEditorBase::createEmpty(void)
{
    ForegroundFieldContainerEditor *returnValue;

    newPtr<ForegroundFieldContainerEditor>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr ForegroundFieldContainerEditorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ForegroundFieldContainerEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ForegroundFieldContainerEditor *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ForegroundFieldContainerEditorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ForegroundFieldContainerEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ForegroundFieldContainerEditor *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ForegroundFieldContainerEditorBase::shallowCopy(void) const
{
    ForegroundFieldContainerEditor *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ForegroundFieldContainerEditor *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

ForegroundFieldContainerEditorBase::ForegroundFieldContainerEditorBase(void) :
    Inherited()
{
}

ForegroundFieldContainerEditorBase::ForegroundFieldContainerEditorBase(const ForegroundFieldContainerEditorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ForegroundFieldContainerEditorBase::~ForegroundFieldContainerEditorBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void ForegroundFieldContainerEditorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ForegroundFieldContainerEditor *pThis = static_cast<ForegroundFieldContainerEditor *>(this);

    pThis->execSync(static_cast<ForegroundFieldContainerEditor *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ForegroundFieldContainerEditorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ForegroundFieldContainerEditor *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ForegroundFieldContainerEditor *>(pRefAspect),
                  dynamic_cast<const ForegroundFieldContainerEditor *>(this));

    return returnValue;
}
#endif

void ForegroundFieldContainerEditorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
