
####### Declaration of functions
FUNCTION(RECURSIVE_DIRECTORY_FIND DIR IGNORE_DIRS_MATCHING STRIP_PATH)
   #Get the source files
   FILE(GLOB HEADERS ${DIR}/[^~]*.h)
   FILE(GLOB SOURCES ${DIR}/[^~]*.cpp)
   FILE(GLOB INLINES ${DIR}/[^~]*.inl)
            
	#Strip the path down to a relative one
	FILE(RELATIVE_PATH THE_SOURCE_GROUP ${STRIP_PATH} ${DIR})
	IF(THE_SOURCE_GROUP)
	   STRING(REPLACE "/" "\\" THE_SOURCE_GROUP ${THE_SOURCE_GROUP})
	ELSE(THE_SOURCE_GROUP)
		SET(THE_SOURCE_GROUP "\\")
	ENDIF(THE_SOURCE_GROUP)


	SOURCE_GROUP(${THE_SOURCE_GROUP} FILES ${HEADERS} ${SOURCES} ${INLINES})
   
	FILE(GLOB THE_DIRS_AND_FILES ${DIR}/*)
   
	FOREACH(THE_PATH ${THE_DIRS_AND_FILES})
	   IF(IS_DIRECTORY ${THE_PATH})
		   IF(${THE_PATH} MATCHES "${IGNORE_DIRS_MATCHING}")
		   ELSE(${THE_PATH} MATCHES "${IGNORE_DIRS_MATCHING}")
				#Call this function on all directories within this one
				RECURSIVE_DIRECTORY_FIND(${THE_PATH} ${IGNORE_DIRS_MATCHING} ${STRIP_PATH})
				
		   ENDIF(${THE_PATH} MATCHES "${IGNORE_DIRS_MATCHING}")
	   ENDIF(IS_DIRECTORY ${THE_PATH})
   ENDFOREACH(THE_PATH in ${THE_DIRS_AND_FILES})
ENDFUNCTION(RECURSIVE_DIRECTORY_FIND DIR IGNOR_DIRS_MATCHING)

