/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class XMLLookAndFeel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGLookAndFeel.h"             // BaseLookAndFeel Class

#include "OSGXMLLookAndFeelBase.h"
#include "OSGXMLLookAndFeel.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::XMLLookAndFeel
    UI XML LookAndFeel.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var LookAndFeel *   XMLLookAndFeelBase::_sfBaseLookAndFeel
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<XMLLookAndFeel *>::_type("XMLLookAndFeelPtr", "LookAndFeelPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(XMLLookAndFeel *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           XMLLookAndFeel *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           XMLLookAndFeel *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void XMLLookAndFeelBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecLookAndFeelPtr::Description(
        SFUnrecLookAndFeelPtr::getClassType(),
        "BaseLookAndFeel",
        "",
        BaseLookAndFeelFieldId, BaseLookAndFeelFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&XMLLookAndFeel::editHandleBaseLookAndFeel),
        static_cast<FieldGetMethodSig >(&XMLLookAndFeel::getHandleBaseLookAndFeel));

    oType.addInitialDesc(pDesc);
}


XMLLookAndFeelBase::TypeObject XMLLookAndFeelBase::_type(
    XMLLookAndFeelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&XMLLookAndFeelBase::createEmptyLocal),
    XMLLookAndFeel::initMethod,
    XMLLookAndFeel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&XMLLookAndFeel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"XMLLookAndFeel\"\n"
    "\tparent=\"LookAndFeel\"\n"
    "    library=\"ContribUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "UI XML LookAndFeel.\n"
    "\t<Field\n"
    "\t\tname=\"BaseLookAndFeel\"\n"
    "\t\ttype=\"LookAndFeel\"\n"
    "\t\tcategory=\"pointer\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"public\"\n"
    "\t\tdefaultValue=\"NULL\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    "UI XML LookAndFeel.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &XMLLookAndFeelBase::getType(void)
{
    return _type;
}

const FieldContainerType &XMLLookAndFeelBase::getType(void) const
{
    return _type;
}

UInt32 XMLLookAndFeelBase::getContainerSize(void) const
{
    return sizeof(XMLLookAndFeel);
}

/*------------------------- decorator get ------------------------------*/


//! Get the XMLLookAndFeel::_sfBaseLookAndFeel field.
const SFUnrecLookAndFeelPtr *XMLLookAndFeelBase::getSFBaseLookAndFeel(void) const
{
    return &_sfBaseLookAndFeel;
}

SFUnrecLookAndFeelPtr *XMLLookAndFeelBase::editSFBaseLookAndFeel(void)
{
    editSField(BaseLookAndFeelFieldMask);

    return &_sfBaseLookAndFeel;
}





/*------------------------------ access -----------------------------------*/

UInt32 XMLLookAndFeelBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (BaseLookAndFeelFieldMask & whichField))
    {
        returnValue += _sfBaseLookAndFeel.getBinSize();
    }

    return returnValue;
}

void XMLLookAndFeelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (BaseLookAndFeelFieldMask & whichField))
    {
        _sfBaseLookAndFeel.copyToBin(pMem);
    }
}

void XMLLookAndFeelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (BaseLookAndFeelFieldMask & whichField))
    {
        _sfBaseLookAndFeel.copyFromBin(pMem);
    }
}

//! create a new instance of the class
XMLLookAndFeelTransitPtr XMLLookAndFeelBase::createLocal(BitVector bFlags)
{
    XMLLookAndFeelTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<XMLLookAndFeel>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
XMLLookAndFeelTransitPtr XMLLookAndFeelBase::createDependent(BitVector bFlags)
{
    XMLLookAndFeelTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<XMLLookAndFeel>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
XMLLookAndFeelTransitPtr XMLLookAndFeelBase::create(void)
{
    XMLLookAndFeelTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<XMLLookAndFeel>(tmpPtr);
    }

    return fc;
}

XMLLookAndFeel *XMLLookAndFeelBase::createEmptyLocal(BitVector bFlags)
{
    XMLLookAndFeel *returnValue;

    newPtr<XMLLookAndFeel>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
XMLLookAndFeel *XMLLookAndFeelBase::createEmpty(void)
{
    XMLLookAndFeel *returnValue;

    newPtr<XMLLookAndFeel>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr XMLLookAndFeelBase::shallowCopyLocal(
    BitVector bFlags) const
{
    XMLLookAndFeel *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const XMLLookAndFeel *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr XMLLookAndFeelBase::shallowCopyDependent(
    BitVector bFlags) const
{
    XMLLookAndFeel *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const XMLLookAndFeel *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr XMLLookAndFeelBase::shallowCopy(void) const
{
    XMLLookAndFeel *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const XMLLookAndFeel *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

XMLLookAndFeelBase::XMLLookAndFeelBase(void) :
    Inherited(),
    _sfBaseLookAndFeel        (NULL)
{
}

XMLLookAndFeelBase::XMLLookAndFeelBase(const XMLLookAndFeelBase &source) :
    Inherited(source),
    _sfBaseLookAndFeel        (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

XMLLookAndFeelBase::~XMLLookAndFeelBase(void)
{
}

void XMLLookAndFeelBase::onCreate(const XMLLookAndFeel *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        XMLLookAndFeel *pThis = static_cast<XMLLookAndFeel *>(this);

        pThis->setBaseLookAndFeel(source->getBaseLookAndFeel());
    }
}

GetFieldHandlePtr XMLLookAndFeelBase::getHandleBaseLookAndFeel (void) const
{
    SFUnrecLookAndFeelPtr::GetHandlePtr returnValue(
        new  SFUnrecLookAndFeelPtr::GetHandle(
             &_sfBaseLookAndFeel,
             this->getType().getFieldDesc(BaseLookAndFeelFieldId),
             const_cast<XMLLookAndFeelBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr XMLLookAndFeelBase::editHandleBaseLookAndFeel(void)
{
    SFUnrecLookAndFeelPtr::EditHandlePtr returnValue(
        new  SFUnrecLookAndFeelPtr::EditHandle(
             &_sfBaseLookAndFeel,
             this->getType().getFieldDesc(BaseLookAndFeelFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&XMLLookAndFeel::setBaseLookAndFeel,
                    static_cast<XMLLookAndFeel *>(this), _1));

    editSField(BaseLookAndFeelFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void XMLLookAndFeelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    XMLLookAndFeel *pThis = static_cast<XMLLookAndFeel *>(this);

    pThis->execSync(static_cast<XMLLookAndFeel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *XMLLookAndFeelBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    XMLLookAndFeel *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const XMLLookAndFeel *>(pRefAspect),
                  dynamic_cast<const XMLLookAndFeel *>(this));

    return returnValue;
}
#endif

void XMLLookAndFeelBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<XMLLookAndFeel *>(this)->setBaseLookAndFeel(NULL);


}


OSG_END_NAMESPACE
