/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDISTRIBUTION2DFIELDS_H_
#define _OSGDISTRIBUTION2DFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribParticleSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class Distribution2D;

OSG_GEN_CONTAINERPTR(Distribution2D);

/*! \ingroup GrpContribParticleSystemFieldTraits
    \ingroup GrpLibOSGContribParticleSystem
 */
template <>
struct FieldTraits<Distribution2D *> :
    public FieldTraitsFCPtrBase<Distribution2D *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<Distribution2D *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBPARTICLESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFDistribution2DPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFDistribution2DPtr"; }
};

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<Distribution2D *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdDistribution2DPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<Distribution2D *,
                      RecordedRefCountPolicy  > SFRecDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<Distribution2D *,
                      UnrecordedRefCountPolicy> SFUnrecDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<Distribution2D *,
                      WeakRefCountPolicy      > SFWeakDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<Distribution2D *,
                      NoRefCountPolicy        > SFUncountedDistribution2DPtr;


/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<Distribution2D *,
                      RecordedRefCountPolicy  > MFRecDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<Distribution2D *,
                      UnrecordedRefCountPolicy> MFUnrecDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<Distribution2D *,
                      WeakRefCountPolicy      > MFWeakDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<Distribution2D *,
                      NoRefCountPolicy        > MFUncountedDistribution2DPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFRecDistribution2DPtr : 
    public PointerSField<Distribution2D *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUnrecDistribution2DPtr : 
    public PointerSField<Distribution2D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFWeakDistribution2DPtr :
    public PointerSField<Distribution2D *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUncountedDistribution2DPtr :
    public PointerSField<Distribution2D *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFRecDistribution2DPtr :
    public PointerMField<Distribution2D *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUnrecDistribution2DPtr :
    public PointerMField<Distribution2D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFWeakDistribution2DPtr :
    public PointerMField<Distribution2D *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUncountedDistribution2DPtr :
    public PointerMField<Distribution2D *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGDISTRIBUTION2DFIELDS_H_ */
