/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGGAUSSIANNORMALDISTRIBUTION2DFIELDS_H_
#define _OSGGAUSSIANNORMALDISTRIBUTION2DFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribParticleSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class GaussianNormalDistribution2D;

OSG_GEN_CONTAINERPTR(GaussianNormalDistribution2D);

/*! \ingroup GrpContribParticleSystemFieldTraits
    \ingroup GrpLibOSGContribParticleSystem
 */
template <>
struct FieldTraits<GaussianNormalDistribution2D *> :
    public FieldTraitsFCPtrBase<GaussianNormalDistribution2D *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<GaussianNormalDistribution2D *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBPARTICLESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFGaussianNormalDistribution2DPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFGaussianNormalDistribution2DPtr"; }
};

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecGaussianNormalDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecGaussianNormalDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakGaussianNormalDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdGaussianNormalDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecGaussianNormalDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecGaussianNormalDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakGaussianNormalDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<GaussianNormalDistribution2D *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdGaussianNormalDistribution2DPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<GaussianNormalDistribution2D *,
                      RecordedRefCountPolicy  > SFRecGaussianNormalDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<GaussianNormalDistribution2D *,
                      UnrecordedRefCountPolicy> SFUnrecGaussianNormalDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<GaussianNormalDistribution2D *,
                      WeakRefCountPolicy      > SFWeakGaussianNormalDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<GaussianNormalDistribution2D *,
                      NoRefCountPolicy        > SFUncountedGaussianNormalDistribution2DPtr;


/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<GaussianNormalDistribution2D *,
                      RecordedRefCountPolicy  > MFRecGaussianNormalDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<GaussianNormalDistribution2D *,
                      UnrecordedRefCountPolicy> MFUnrecGaussianNormalDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<GaussianNormalDistribution2D *,
                      WeakRefCountPolicy      > MFWeakGaussianNormalDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<GaussianNormalDistribution2D *,
                      NoRefCountPolicy        > MFUncountedGaussianNormalDistribution2DPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFRecGaussianNormalDistribution2DPtr : 
    public PointerSField<GaussianNormalDistribution2D *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUnrecGaussianNormalDistribution2DPtr : 
    public PointerSField<GaussianNormalDistribution2D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFWeakGaussianNormalDistribution2DPtr :
    public PointerSField<GaussianNormalDistribution2D *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUncountedGaussianNormalDistribution2DPtr :
    public PointerSField<GaussianNormalDistribution2D *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFRecGaussianNormalDistribution2DPtr :
    public PointerMField<GaussianNormalDistribution2D *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUnrecGaussianNormalDistribution2DPtr :
    public PointerMField<GaussianNormalDistribution2D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFWeakGaussianNormalDistribution2DPtr :
    public PointerMField<GaussianNormalDistribution2D *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUncountedGaussianNormalDistribution2DPtr :
    public PointerMField<GaussianNormalDistribution2D *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGGAUSSIANNORMALDISTRIBUTION2DFIELDS_H_ */
