/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTRIDISTRIBUTION2DFIELDS_H_
#define _OSGTRIDISTRIBUTION2DFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribParticleSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TriDistribution2D;

OSG_GEN_CONTAINERPTR(TriDistribution2D);

/*! \ingroup GrpContribParticleSystemFieldTraits
    \ingroup GrpLibOSGContribParticleSystem
 */
template <>
struct FieldTraits<TriDistribution2D *> :
    public FieldTraitsFCPtrBase<TriDistribution2D *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TriDistribution2D *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBPARTICLESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTriDistribution2DPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTriDistribution2DPtr"; }
};

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTriDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTriDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTriDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTriDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTriDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTriDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTriDistribution2DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution2D *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTriDistribution2DPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution2D *,
                      RecordedRefCountPolicy  > SFRecTriDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution2D *,
                      UnrecordedRefCountPolicy> SFUnrecTriDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution2D *,
                      WeakRefCountPolicy      > SFWeakTriDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution2D *,
                      NoRefCountPolicy        > SFUncountedTriDistribution2DPtr;


/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution2D *,
                      RecordedRefCountPolicy  > MFRecTriDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution2D *,
                      UnrecordedRefCountPolicy> MFUnrecTriDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution2D *,
                      WeakRefCountPolicy      > MFWeakTriDistribution2DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution2D *,
                      NoRefCountPolicy        > MFUncountedTriDistribution2DPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFRecTriDistribution2DPtr : 
    public PointerSField<TriDistribution2D *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUnrecTriDistribution2DPtr : 
    public PointerSField<TriDistribution2D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFWeakTriDistribution2DPtr :
    public PointerSField<TriDistribution2D *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUncountedTriDistribution2DPtr :
    public PointerSField<TriDistribution2D *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFRecTriDistribution2DPtr :
    public PointerMField<TriDistribution2D *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUnrecTriDistribution2DPtr :
    public PointerMField<TriDistribution2D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFWeakTriDistribution2DPtr :
    public PointerMField<TriDistribution2D *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUncountedTriDistribution2DPtr :
    public PointerMField<TriDistribution2D *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTRIDISTRIBUTION2DFIELDS_H_ */
