/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMOUSEWHEELEVENTDETAILSFIELDS_H_
#define _OSGMOUSEWHEELEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class MouseWheelEventDetails;

OSG_GEN_CONTAINERPTR(MouseWheelEventDetails);

/*! \ingroup GrpSystemFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<MouseWheelEventDetails *> :
    public FieldTraitsFCPtrBase<MouseWheelEventDetails *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<MouseWheelEventDetails *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFMouseWheelEventDetailsPtr"; }
};

template<> inline
const Char8 *FieldTraits<MouseWheelEventDetails *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMouseWheelEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<MouseWheelEventDetails *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMouseWheelEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<MouseWheelEventDetails *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMouseWheelEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<MouseWheelEventDetails *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMouseWheelEventDetailsPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MouseWheelEventDetails *,
                      RecordedRefCountPolicy  > SFRecMouseWheelEventDetailsPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MouseWheelEventDetails *,
                      UnrecordedRefCountPolicy> SFUnrecMouseWheelEventDetailsPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MouseWheelEventDetails *,
                      WeakRefCountPolicy      > SFWeakMouseWheelEventDetailsPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MouseWheelEventDetails *,
                      NoRefCountPolicy        > SFUncountedMouseWheelEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecMouseWheelEventDetailsPtr : 
    public PointerSField<MouseWheelEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecMouseWheelEventDetailsPtr : 
    public PointerSField<MouseWheelEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakMouseWheelEventDetailsPtr :
    public PointerSField<MouseWheelEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedMouseWheelEventDetailsPtr :
    public PointerSField<MouseWheelEventDetails *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMOUSEWHEELEVENTDETAILSFIELDS_H_ */
