/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class UIDrawObjectCanvas
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGUIDRAWOBJECTCANVASBASE_H_
#define _OSGUIDRAWOBJECTCANVASBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribUserInterfaceDef.h"

//#include "OSGBaseTypes.h"

#include "OSGComponent.h" // Parent

#include "OSGUIDrawObjectFields.h"      // DrawObjects type
#include "OSGSysFields.h"               // UsePreferredSizeAsRequested type

#include "OSGUIDrawObjectCanvasFields.h"

OSG_BEGIN_NAMESPACE

class UIDrawObjectCanvas;

//! \brief UIDrawObjectCanvas Base Class.

class OSG_CONTRIBUSERINTERFACE_DLLMAPPING UIDrawObjectCanvasBase : public Component
{
  public:

    typedef Component Inherited;
    typedef Component ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(UIDrawObjectCanvas);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        DrawObjectsFieldId = Inherited::NextFieldId,
        UsePreferredSizeAsRequestedFieldId = DrawObjectsFieldId + 1,
        NextFieldId = UsePreferredSizeAsRequestedFieldId + 1
    };

    static const OSG::BitVector DrawObjectsFieldMask =
        (TypeTraits<BitVector>::One << DrawObjectsFieldId);
    static const OSG::BitVector UsePreferredSizeAsRequestedFieldMask =
        (TypeTraits<BitVector>::One << UsePreferredSizeAsRequestedFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef MFUnrecUIDrawObjectPtr MFDrawObjectsType;
    typedef SFBool            SFUsePreferredSizeAsRequestedType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

            const MFUnrecUIDrawObjectPtr *getMFDrawObjects    (void) const;
                  MFUnrecUIDrawObjectPtr *editMFDrawObjects    (void);

                  SFBool              *editSFUsePreferredSizeAsRequested(void);
            const SFBool              *getSFUsePreferredSizeAsRequested (void) const;


                  UIDrawObject * getDrawObjects    (const UInt32 index) const;

                  bool                &editUsePreferredSizeAsRequested(void);
                  bool                 getUsePreferredSizeAsRequested (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setUsePreferredSizeAsRequested(const bool value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    void pushToDrawObjects           (UIDrawObject * const value   );
    void assignDrawObjects          (const MFUnrecUIDrawObjectPtr &value);
    void removeFromDrawObjects (UInt32               uiIndex );
    void removeObjFromDrawObjects(UIDrawObject * const value   );
    void clearDrawObjects            (void                         );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  UIDrawObjectCanvasTransitPtr  create          (void);
    static  UIDrawObjectCanvas           *createEmpty     (void);

    static  UIDrawObjectCanvasTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  UIDrawObjectCanvas            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  UIDrawObjectCanvasTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    MFUnrecUIDrawObjectPtr _mfDrawObjects;
    SFBool            _sfUsePreferredSizeAsRequested;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    UIDrawObjectCanvasBase(void);
    UIDrawObjectCanvasBase(const UIDrawObjectCanvasBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~UIDrawObjectCanvasBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const UIDrawObjectCanvas *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleDrawObjects     (void) const;
    EditFieldHandlePtr editHandleDrawObjects    (void);
    GetFieldHandlePtr  getHandleUsePreferredSizeAsRequested (void) const;
    EditFieldHandlePtr editHandleUsePreferredSizeAsRequested(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      UIDrawObjectCanvasBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const UIDrawObjectCanvasBase &source);
};

typedef UIDrawObjectCanvasBase *UIDrawObjectCanvasBaseP;

OSG_END_NAMESPACE

#endif /* _OSGUIDRAWOBJECTCANVASBASE_H_ */
