/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTRIDISTRIBUTION3DFIELDS_H_
#define _OSGTRIDISTRIBUTION3DFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribParticleSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TriDistribution3D;

OSG_GEN_CONTAINERPTR(TriDistribution3D);

/*! \ingroup GrpContribParticleSystemFieldTraits
    \ingroup GrpLibOSGContribParticleSystem
 */
template <>
struct FieldTraits<TriDistribution3D *> :
    public FieldTraitsFCPtrBase<TriDistribution3D *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TriDistribution3D *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBPARTICLESYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTriDistribution3DPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTriDistribution3DPtr"; }
};

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTriDistribution3DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTriDistribution3DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTriDistribution3DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTriDistribution3DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTriDistribution3DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTriDistribution3DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTriDistribution3DPtr"; 
}

template<> inline
const Char8 *FieldTraits<TriDistribution3D *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTriDistribution3DPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution3D *,
                      RecordedRefCountPolicy  > SFRecTriDistribution3DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution3D *,
                      UnrecordedRefCountPolicy> SFUnrecTriDistribution3DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution3D *,
                      WeakRefCountPolicy      > SFWeakTriDistribution3DPtr;
/*! \ingroup GrpContribParticleSystemFieldSFields */
typedef PointerSField<TriDistribution3D *,
                      NoRefCountPolicy        > SFUncountedTriDistribution3DPtr;


/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution3D *,
                      RecordedRefCountPolicy  > MFRecTriDistribution3DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution3D *,
                      UnrecordedRefCountPolicy> MFUnrecTriDistribution3DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution3D *,
                      WeakRefCountPolicy      > MFWeakTriDistribution3DPtr;
/*! \ingroup GrpContribParticleSystemFieldMFields */
typedef PointerMField<TriDistribution3D *,
                      NoRefCountPolicy        > MFUncountedTriDistribution3DPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFRecTriDistribution3DPtr : 
    public PointerSField<TriDistribution3D *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUnrecTriDistribution3DPtr : 
    public PointerSField<TriDistribution3D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFWeakTriDistribution3DPtr :
    public PointerSField<TriDistribution3D *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldSFields \ingroup GrpLibOSGContribParticleSystem */
struct SFUncountedTriDistribution3DPtr :
    public PointerSField<TriDistribution3D *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFRecTriDistribution3DPtr :
    public PointerMField<TriDistribution3D *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUnrecTriDistribution3DPtr :
    public PointerMField<TriDistribution3D *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFWeakTriDistribution3DPtr :
    public PointerMField<TriDistribution3D *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribParticleSystemFieldMFields \ingroup GrpLibOSGContribParticleSystem */
struct MFUncountedTriDistribution3DPtr :
    public PointerMField<TriDistribution3D *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTRIDISTRIBUTION3DFIELDS_H_ */
