/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com),  Behboud Kalantary         *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPHYSICSLMOTORJOINTFIELDS_H_
#define _OSGPHYSICSLMOTORJOINTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribPhysicsDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PhysicsLMotorJoint;

OSG_GEN_CONTAINERPTR(PhysicsLMotorJoint);

/*! \ingroup GrpContribPhysicsFieldTraits
    \ingroup GrpLibOSGContribPhysics
 */
template <>
struct FieldTraits<PhysicsLMotorJoint *> :
    public FieldTraitsFCPtrBase<PhysicsLMotorJoint *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PhysicsLMotorJoint *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBPHYSICS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPhysicsLMotorJointPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPhysicsLMotorJointPtr"; }
};

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPhysicsLMotorJointPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPhysicsLMotorJointPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPhysicsLMotorJointPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPhysicsLMotorJointPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPhysicsLMotorJointPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPhysicsLMotorJointPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPhysicsLMotorJointPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsLMotorJoint *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPhysicsLMotorJointPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsLMotorJoint *,
                      RecordedRefCountPolicy  > SFRecPhysicsLMotorJointPtr;
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsLMotorJoint *,
                      UnrecordedRefCountPolicy> SFUnrecPhysicsLMotorJointPtr;
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsLMotorJoint *,
                      WeakRefCountPolicy      > SFWeakPhysicsLMotorJointPtr;
/*! \ingroup GrpContribPhysicsFieldSFields */
typedef PointerSField<PhysicsLMotorJoint *,
                      NoRefCountPolicy        > SFUncountedPhysicsLMotorJointPtr;


/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsLMotorJoint *,
                      RecordedRefCountPolicy  > MFRecPhysicsLMotorJointPtr;
/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsLMotorJoint *,
                      UnrecordedRefCountPolicy> MFUnrecPhysicsLMotorJointPtr;
/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsLMotorJoint *,
                      WeakRefCountPolicy      > MFWeakPhysicsLMotorJointPtr;
/*! \ingroup GrpContribPhysicsFieldMFields */
typedef PointerMField<PhysicsLMotorJoint *,
                      NoRefCountPolicy        > MFUncountedPhysicsLMotorJointPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFRecPhysicsLMotorJointPtr : 
    public PointerSField<PhysicsLMotorJoint *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFUnrecPhysicsLMotorJointPtr : 
    public PointerSField<PhysicsLMotorJoint *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFWeakPhysicsLMotorJointPtr :
    public PointerSField<PhysicsLMotorJoint *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldSFields \ingroup GrpLibOSGContribPhysics */
struct SFUncountedPhysicsLMotorJointPtr :
    public PointerSField<PhysicsLMotorJoint *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFRecPhysicsLMotorJointPtr :
    public PointerMField<PhysicsLMotorJoint *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFUnrecPhysicsLMotorJointPtr :
    public PointerMField<PhysicsLMotorJoint *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFWeakPhysicsLMotorJointPtr :
    public PointerMField<PhysicsLMotorJoint *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribPhysicsFieldMFields \ingroup GrpLibOSGContribPhysics */
struct MFUncountedPhysicsLMotorJointPtr :
    public PointerMField<PhysicsLMotorJoint *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPHYSICSLMOTORJOINTFIELDS_H_ */
