/*---------------------------------------------------------------------------*\
 *                     OpenSG ToolBox UserInterface                          *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala, Alden Peterson, Lee Zaniewski, Jonathan Flory    *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DefaultMutableTreeNode
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDEFAULTMUTABLETREENODEBASE_H_
#define _OSGDEFAULTMUTABLETREENODEBASE_H_
#ifdef __sgi
#pragma once
#endif


#include <OpenSG/OSGConfig.h>
#include "OSGUserInterfaceDef.h"

#include <OpenSG/OSGBaseTypes.h>
#include <OpenSG/OSGRefPtr.h>
#include <OpenSG/OSGCoredNodePtr.h>

#include "OSGMutableTreeNode.h" // Parent

#include <OpenSG/OSGBoolFields.h> // AllowsChildrenInternal type
#include "Component/Tree/Model/OSGMutableTreeNodeFields.h" // ChildrenInternal type
#include "Component/Tree/Model/OSGMutableTreeNodeFields.h" // ParentInternal type

#include "OSGDefaultMutableTreeNodeFields.h"

OSG_BEGIN_NAMESPACE

class DefaultMutableTreeNode;
class BinaryDataHandler;

//! \brief DefaultMutableTreeNode Base Class.

class OSG_USERINTERFACELIB_DLLMAPPING DefaultMutableTreeNodeBase : public MutableTreeNode
{
  private:

    typedef MutableTreeNode    Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    typedef DefaultMutableTreeNodePtr  Ptr;

    enum
    {
        AllowsChildrenInternalFieldId = Inherited::NextFieldId,
        ChildrenInternalFieldId       = AllowsChildrenInternalFieldId + 1,
        ParentInternalFieldId         = ChildrenInternalFieldId       + 1,
        NextFieldId                   = ParentInternalFieldId         + 1
    };

    static const OSG::BitVector AllowsChildrenInternalFieldMask;
    static const OSG::BitVector ChildrenInternalFieldMask;
    static const OSG::BitVector ParentInternalFieldMask;


    static const OSG::BitVector MTInfluenceMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static        FieldContainerType &getClassType    (void); 
    static        UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

           SFBool              *getSFAllowsChildrenInternal(void);
           MFMutableTreeNodePtr *getMFChildrenInternal(void);
           SFMutableTreeNodePtr *getSFParentInternal (void);

           bool                &getAllowsChildrenInternal(void);
     const bool                &getAllowsChildrenInternal(void) const;
           MutableTreeNodePtr  &getParentInternal (void);
     const MutableTreeNodePtr  &getParentInternal (void) const;
           MutableTreeNodePtr  &getChildrenInternal(const UInt32 index);
           MFMutableTreeNodePtr &getChildrenInternal(void);
     const MFMutableTreeNodePtr &getChildrenInternal(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

     void setAllowsChildrenInternal( const bool &value );
     void setParentInternal ( const MutableTreeNodePtr &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (const BitVector         &whichField);
    virtual void   copyToBin  (      BinaryDataHandler &pMem,
                               const BitVector         &whichField);
    virtual void   copyFromBin(      BinaryDataHandler &pMem,
                               const BitVector         &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  DefaultMutableTreeNodePtr      create          (void); 
    static  DefaultMutableTreeNodePtr      createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFBool              _sfAllowsChildrenInternal;
    MFMutableTreeNodePtr   _mfChildrenInternal;
    SFMutableTreeNodePtr   _sfParentInternal;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    DefaultMutableTreeNodeBase(void);
    DefaultMutableTreeNodeBase(const DefaultMutableTreeNodeBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~DefaultMutableTreeNodeBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#if !defined(OSG_FIXED_MFIELDSYNC)
    void executeSyncImpl(      DefaultMutableTreeNodeBase *pOther,
                         const BitVector         &whichField);

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField);
#else
    void executeSyncImpl(      DefaultMutableTreeNodeBase *pOther,
                         const BitVector         &whichField,
                         const SyncInfo          &sInfo     );

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField,
                               const SyncInfo          &sInfo);

    virtual void execBeginEdit     (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

            void execBeginEditImpl (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

    virtual void onDestroyAspect(UInt32 uiId, UInt32 uiAspect);
#endif

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const DefaultMutableTreeNodeBase &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef DefaultMutableTreeNodeBase *DefaultMutableTreeNodeBaseP;

typedef osgIF<DefaultMutableTreeNodeBase::isNodeCore,
              CoredNodePtr<DefaultMutableTreeNode>,
              FieldContainer::attempt_to_create_CoredNodePtr_on_non_NodeCore_FC
              >::_IRet DefaultMutableTreeNodeNodePtr;

typedef RefPtr<DefaultMutableTreeNodePtr> DefaultMutableTreeNodeRefPtr;

OSG_END_NAMESPACE

#define OSGDEFAULTMUTABLETREENODEBASE_HEADER_CVSID "@(#)$Id: FCBaseTemplate_h.h,v 1.40 2005/07/20 00:10:14 vossg Exp $"

#endif /* _OSGDEFAULTMUTABLETREENODEBASE_H_ */
