/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2002 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class LinearPositionalAttribute!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILELINEARPOSITIONALATTRIBUTEINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "OSGLinearPositionalAttributeBase.h"
#include "OSGLinearPositionalAttribute.h"


OSG_USING_NAMESPACE

const OSG::BitVector  LinearPositionalAttributeBase::PositionFieldMask = 
    (TypeTraits<BitVector>::One << LinearPositionalAttributeBase::PositionFieldId);

const OSG::BitVector  LinearPositionalAttributeBase::VelocityFieldMask = 
    (TypeTraits<BitVector>::One << LinearPositionalAttributeBase::VelocityFieldId);

const OSG::BitVector  LinearPositionalAttributeBase::AccelerationFieldMask = 
    (TypeTraits<BitVector>::One << LinearPositionalAttributeBase::AccelerationFieldId);

const OSG::BitVector LinearPositionalAttributeBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var Pnt3f           LinearPositionalAttributeBase::_sfPosition
    
*/
/*! \var Vec3f           LinearPositionalAttributeBase::_sfVelocity
    
*/
/*! \var Vec3f           LinearPositionalAttributeBase::_sfAcceleration
    
*/

//! LinearPositionalAttribute description

FieldDescription *LinearPositionalAttributeBase::_desc[] = 
{
    new FieldDescription(SFPnt3f::getClassType(), 
                     "Position", 
                     PositionFieldId, PositionFieldMask,
                     false,
                     (FieldAccessMethod) &LinearPositionalAttributeBase::getSFPosition),
    new FieldDescription(SFVec3f::getClassType(), 
                     "Velocity", 
                     VelocityFieldId, VelocityFieldMask,
                     false,
                     (FieldAccessMethod) &LinearPositionalAttributeBase::getSFVelocity),
    new FieldDescription(SFVec3f::getClassType(), 
                     "Acceleration", 
                     AccelerationFieldId, AccelerationFieldMask,
                     false,
                     (FieldAccessMethod) &LinearPositionalAttributeBase::getSFAcceleration)
};


FieldContainerType LinearPositionalAttributeBase::_type(
    "LinearPositionalAttribute",
    "PhysicsObjectAttribute",
    NULL,
    (PrototypeCreateF) &LinearPositionalAttributeBase::createEmpty,
    LinearPositionalAttribute::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(LinearPositionalAttributeBase, LinearPositionalAttributePtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &LinearPositionalAttributeBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &LinearPositionalAttributeBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr LinearPositionalAttributeBase::shallowCopy(void) const 
{ 
    LinearPositionalAttributePtr returnValue; 

    newPtr(returnValue, dynamic_cast<const LinearPositionalAttribute *>(this)); 

    return returnValue; 
}

UInt32 LinearPositionalAttributeBase::getContainerSize(void) const 
{ 
    return sizeof(LinearPositionalAttribute); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void LinearPositionalAttributeBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((LinearPositionalAttributeBase *) &other, whichField);
}
#else
void LinearPositionalAttributeBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((LinearPositionalAttributeBase *) &other, whichField, sInfo);
}
void LinearPositionalAttributeBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void LinearPositionalAttributeBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

LinearPositionalAttributeBase::LinearPositionalAttributeBase(void) :
    _sfPosition               (), 
    _sfVelocity               (), 
    _sfAcceleration           (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

LinearPositionalAttributeBase::LinearPositionalAttributeBase(const LinearPositionalAttributeBase &source) :
    _sfPosition               (source._sfPosition               ), 
    _sfVelocity               (source._sfVelocity               ), 
    _sfAcceleration           (source._sfAcceleration           ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

LinearPositionalAttributeBase::~LinearPositionalAttributeBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 LinearPositionalAttributeBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (PositionFieldMask & whichField))
    {
        returnValue += _sfPosition.getBinSize();
    }

    if(FieldBits::NoField != (VelocityFieldMask & whichField))
    {
        returnValue += _sfVelocity.getBinSize();
    }

    if(FieldBits::NoField != (AccelerationFieldMask & whichField))
    {
        returnValue += _sfAcceleration.getBinSize();
    }


    return returnValue;
}

void LinearPositionalAttributeBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (PositionFieldMask & whichField))
    {
        _sfPosition.copyToBin(pMem);
    }

    if(FieldBits::NoField != (VelocityFieldMask & whichField))
    {
        _sfVelocity.copyToBin(pMem);
    }

    if(FieldBits::NoField != (AccelerationFieldMask & whichField))
    {
        _sfAcceleration.copyToBin(pMem);
    }


}

void LinearPositionalAttributeBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (PositionFieldMask & whichField))
    {
        _sfPosition.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (VelocityFieldMask & whichField))
    {
        _sfVelocity.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (AccelerationFieldMask & whichField))
    {
        _sfAcceleration.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void LinearPositionalAttributeBase::executeSyncImpl(      LinearPositionalAttributeBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (PositionFieldMask & whichField))
        _sfPosition.syncWith(pOther->_sfPosition);

    if(FieldBits::NoField != (VelocityFieldMask & whichField))
        _sfVelocity.syncWith(pOther->_sfVelocity);

    if(FieldBits::NoField != (AccelerationFieldMask & whichField))
        _sfAcceleration.syncWith(pOther->_sfAcceleration);


}
#else
void LinearPositionalAttributeBase::executeSyncImpl(      LinearPositionalAttributeBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (PositionFieldMask & whichField))
        _sfPosition.syncWith(pOther->_sfPosition);

    if(FieldBits::NoField != (VelocityFieldMask & whichField))
        _sfVelocity.syncWith(pOther->_sfVelocity);

    if(FieldBits::NoField != (AccelerationFieldMask & whichField))
        _sfAcceleration.syncWith(pOther->_sfAcceleration);



}

void LinearPositionalAttributeBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<LinearPositionalAttributePtr>::_type("LinearPositionalAttributePtr", "PhysicsObjectAttributePtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(LinearPositionalAttributePtr, );
OSG_DLLEXPORT_MFIELD_DEF1(LinearPositionalAttributePtr, );

OSG_END_NAMESPACE


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: FCBaseTemplate_cpp.h,v 1.45 2005/07/20 00:10:14 vossg Exp $";
    static Char8 cvsid_hpp       [] = OSGLINEARPOSITIONALATTRIBUTEBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGLINEARPOSITIONALATTRIBUTEBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGLINEARPOSITIONALATTRIBUTEFIELDS_HEADER_CVSID;
}

