###

LIB_NAME = OSGParticleSystem
LIB_INCLUDE_DIR_NAME = ParticleSystem

srcdir = ../../../src
installdir = ../../../../Builds/Linux
commondir = ../../../../Builds/Common
VPATH = $(srcdir)/:$(srcdir)/ParticleSystem:$(srcdir)/ParticleSystem/ParticleEffectors:$(srcdir)/ParticleSystem/MultiParticleSystemEffectors:$(srcdir)/ParticleSystem/ParticleSystemEffectors:$(srcdir)/ParticleSystem/ParticleGenerators:$(srcdir)/ParticleSystem/ParticleSystemDrawers:$(srcdir)/ParticleSystem/Events:$(srcdir)/ListType:


#.SUFFIX = .o .o

EXTRA_CCFLAGS = -I$(srcdir)

OBJECTS = OSGParticleSystemBase.o \
	OSGParticleSystemCore.o \
	OSGParticleSystem.o \
	OSGParticleSystemCoreBase.o \
	OSGParticleEffectorBase.o \
	OSGParticleEffector.o \
	OSGMultiParticleSystemEffectorBase.o \
	OSGMultiParticleSystemEffector.o \
	OSGParticleSystemEffector.o \
	OSGParticleSystemEffectorBase.o \
	OSGParticleGeneratorBase.o \
	OSGParticleGenerator.o \
	OSGShaderQuadParticleSystemDrawerBase.o \
	OSGBaseQuadParticleSystemDrawerBase.o \
	OSGParticleSystemDrawerBase.o \
	OSGPointParticleSystemDrawer.o \
	OSGVelocityQuadParticleSystemDrawer.o \
	OSGQuadParticleSystemDrawerBase.o \
	OSGNodeParticleSystemDrawerBase.o \
	OSGNodeParticleSystemDrawer.o \
	OSGQuadParticleSystemDrawer.o \
	OSGViewDirQuadParticleSystemDrawerBase.o \
	OSGParticleSystemDrawer.o \
	OSGViewPosQuadParticleSystemDrawer.o \
	OSGViewPosQuadParticleSystemDrawerBase.o \
	OSGViewDirQuadParticleSystemDrawer.o \
	OSGLineParticleSystemDrawerBase.o \
	OSGShaderQuadParticleSystemDrawer.o \
	OSGPointParticleSystemDrawerBase.o \
	OSGBaseQuadParticleSystemDrawer.o \
	OSGLineParticleSystemDrawer.o \
	OSGVelocityQuadParticleSystemDrawerBase.o \
	OSGListTypes.o
        
        
include $(commondir)/CommonMake.mk
