
MESSAGE(STATUS "Prepare OSGContribLua")

GET_FILENAME_COMPONENT(_CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${_CMAKE_CURRENT_LIST_DIR}/CMake")

INCLUDE(ConfigurePackages.OSGContribLua)

OSG_CONFIGURE_LUA()

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_LUA 1")

OSG_OPTION(OSG_LUA_BUILD_WITH_DEBUGGER      "Build Lua with debugging support" OFF)
IF(OSG_LUA_BUILD_WITH_DEBUGGER)
    OSG_SET(OSG_WITH_LUA_DEBUGGER 1)
ELSE()
    OSG_SET(OSG_WITH_LUA_DEBUGGER 0)
ENDIF()

LIST(APPEND OSG_ADDITIONAL_CONFIGURE_LINES "#cmakedefine OSG_WITH_LUA_DEBUGGER 1")

#IF(UNIX)
#  OSG_ADD_OPT(LUA_LIBRARIES)
#  OSG_ADD_OPT(LUA_INCLUDE_DIR)
#ENDIF(UNIX)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/FindLua.cmake"
        DESTINATION share/OpenSG/cmake)

INSTALL(FILES "${_CMAKE_CURRENT_LIST_DIR}/CMake/ConfigurePackages.OSGContribLua.cmake"
        DESTINATION share/OpenSG/cmake)
